declare @correct int=(select catid from cat where catname='correct')
declare @incorrect int=(select catid from cat where catname='incorrect')
declare @actid int
declare @catid int=104
declare @qid int

insert into act(act_cat,actname) values(@catid,'Module 1. Impact of Digital Technology Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'(True or False) A microprocessor is the “brains” of a computer.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'(True or False) Embedded computers are standalone products that have many functions.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'The basic premise of blank 1 is that objects can be tagged, tracked, and monitored through a local network, or across the Internet.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'intelligent workspaces')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the digital divide')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the Internet of Things',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'artificial intelligence')

insert into q(q_act,qname) values(@actid,'(True or False) Computers with AI use human intelligence to make decisions.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) A digital citizen uses technology to be productive and efficient.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'(True or False) A kiosk is a freestanding booth usually placed in a public area that can contain a display device used to show information to the public or event attendees.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'blank 1 are smart devices that respond to a user’s verbal commands by using search technology to provide an answer to a question or perform a task.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'ATMs')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Green computers')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Integrated circuits')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Digital assistants',@correct)

insert into q(q_act,qname) values(@actid,'blank 1 text is descriptive text added to an object.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Associative')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Alternative',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Accessible')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Assistive')

insert into q(q_act,qname) values(@actid,'(True or False) The ENERGY STAR program encourages manufacturers to reduce the amount of electricity used by computers and related devices.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'BYOD stands for Bring Your Own blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Device',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Daily planner')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Database')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Data')

insert into q(q_act,qname) values(@actid,'(True or False) An intelligent classroom is one in which technology is used to facilitate learning and communication.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'Colleges use blank 1 management systems (LMSs) to set up web-based training sites where students can check their progress in a course, take practice tests, and exchange messages with the instructor or other students.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'learning',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'linked')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'locational')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'live')

insert into q(q_act,qname) values(@actid,'(True or False) Automated vehicles decrease independent transportation options for people with disabilities.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) The mobile health (mHealth) trend refers to doctors and nurses using smartphones or tablets to access health records stored on mobile devices.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'A company’s computers monitor assembly lines and equipment using blank 1 communications.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'CAM')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'AI')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'IT')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'M2M',@correct)

insert into q(q_act,qname) values(@actid,'A company’s blank 1 department oversees the centralized computer equipment and administers the network.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'operations',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'management')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'technical support')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'information security')

insert into q(q_act,qname) values(@actid,'(True or False) When looking for a job, you should use humorous or informal names for your account profiles, blog, or domain name to make yourself stand out.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into act(act_cat,actname) values(@catid,'Module 2. The Web Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'Each webpage is assigned a(n) blank 1, an address that identifies the location of the page on the Internet.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Internet Protocol (IP)')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'uniform resource locator (URL)',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'top-level domain (TLD)')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Hypertext Transfer Protocol (HTTP)')

insert into q(q_act,qname) values(@actid,'In the web address www.microsoft.com, the “.com” is the blank 1 meaning blank 2.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'web server name; World Wide Web')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'pathname; location of the webpage')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'top-level domain (TLD); commercial enterprise',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'domain name; name of the organization')

insert into q(q_act,qname) values(@actid,'(True or False) The Internet Engineering Task Force (IETF) sets standards for webpage design.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'A(n) blank 1 website gathers, organizes, and then distributes web content.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'content aggregator',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'media sharing')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'entertainment')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'search engine')

insert into q(q_act,qname) values(@actid,'(True or False) You must be online to use web apps.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'On a webpage, a blank 1 provides supplemental material such as social networking feeds and ads.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'navigation bar')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'header')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'footer')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'sidebar',@correct)

insert into q(q_act,qname) values(@actid,'Which of the following indicates a secure website connection?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'https in the URL',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'http in the URL')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the message “secure website” in the address bar')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a shield icon in the address bar')

insert into q(q_act,qname) values(@actid,'Which of the following is not an advantage of e-commerce for consumers?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You save time by visiting websites instead of stores.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You have little risk of having your credit card number intercepted.',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You can choose goods from any vendor in the world.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You can shop no matter your location, time of day, or conditions.')

insert into q(q_act,qname) values(@actid,'Which of the following describes business-to-business (B2B) e-commerce purchases?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'The consumer is the decision maker.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Pricing can vary for each customer.',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Customers bid on items being sold by other customers.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Customers can pick up the purchased item in a physical store.')

insert into q(q_act,qname) values(@actid,'A business-to-consumer (B2C) website tracks the items you place in a shopping cart using blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'an electronic wallet')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the Transport Layer Security (TLS) protocol')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'crawlers')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'cookies',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) A digital coupon provides a promotional code you enter when you check out and pay for online purchases.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'If you have blank 1, you can evaluate whether information is misleading, biased, or out of date.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'information protocols')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'technical proficiency')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'information security')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'information literacy',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) When you perform a search, a general search engine searches the entire Internet.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Who or what creates the index for a web directory?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a digital spider')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a human editor',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a wiki')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a search operator')

insert into q(q_act,qname) values(@actid,'Which search operator would you use to locate webpages containing the exact phrase augmented reality, with words in the same order?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'augmented + reality')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'– augmented reality')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'“augmented reality”',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'~augmented reality~')

insert into q(q_act,qname) values(@actid,'Which of the following is an example of a specialty search engine?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Bing')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Wolfram Alpha',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Google')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'NexTag')

insert into q(q_act,qname) values(@actid,'Checking a website author’s credentials is one way to establish a site’s blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'copyright')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'information literacy')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'credibility',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'security')

insert into q(q_act,qname) values(@actid,'Which of the following lets you use a sentence or paragraph of text without permission if you include a citation to its source?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'fair use doctrine',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Creative Commons')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'CARS checklist')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'citation style')

insert into q(q_act,qname) values(@actid,'Plagiarism is best defined as blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'moral principles that govern our behavior')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the act of citing sources')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'using another’s work and claiming it as your own',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'rights belonging to a work’s creator')

insert into act(act_cat,actname) values(@catid,'Module 3. Computer Hardware Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'(True or False) Flash memory is a type of volatile memory.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) Volatile memory loses its contents when power is removed.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'(True or False) In an 8-bit coding scheme, 8 bits can represent one character.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'Which of the following storage devices requires an Internet connection?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'internal hard drive')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'cloud storage',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'solid state drive')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'flash memory')

insert into q(q_act,qname) values(@actid,'In which of the following types of computers is the system unit in separate housing from the monitor?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'desktop computer',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'all-in-one computer')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'laptop computer')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'tablet')

insert into q(q_act,qname) values(@actid,'(True or False) In general, a high-powered processor is not necessary for a computer that will be used primarily to check email and browse the web.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'All of the following are pointing devices except:')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'trackball')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'touchpad')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'mouse',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'touchpointer')

insert into q(q_act,qname) values(@actid,'(True or False) Plotters are small, lightweight printers that easily can be connected to mobile devices.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Which of the following tells your computer how to connect to devices you might connect?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'device manager')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'device driver',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'configuration manager')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'communication manager')

insert into q(q_act,qname) values(@actid,'(True or False) The speed at which data travels on a bus is referred to as the word size.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Under which of the following circumstances might you be most likely to contact a professional to repair your computer or mobile device?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'screen is broken',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'computer cannot synchronize with Bluetooth accessories')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'computer or device is too hot')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'printer will not print')

insert into q(q_act,qname) values(@actid,'(True or False) Uninterruptable power supplies and surge suppressors will help protect your computer from power outages.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'If you are experiencing display problems on your computer, which of the following troubleshooting techniques might you attempt first?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Contact a professional for assistance.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Replace the cables.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Check to see that all cables are properly connected.',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Purchase a new monitor.')

insert into act(act_cat,actname) values(@catid,'Module 4. Operating Systems and File Management Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'(True or False) An operating system is a program that manages the complete operation of your computer or mobile device and lets you interact with it.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'GUI stands for blank 1 user interface.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Google')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'graphical',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'government')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'general')

insert into q(q_act,qname) values(@actid,'(True or False) A data file contains the instructions your computer or device needs to run programs and apps.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) The operating system manages interactions between hardware and software.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'Which of the following is NOT true about RAM?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Every program and app requires RAM.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'The system can assign virtual memory to function as RAM.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'RAM is nonvolatile memory.',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'RAM stores open apps and document data while a computer or device is on.')

insert into q(q_act,qname) values(@actid,'(True or False) The kernel is the core of an operating system.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'blank 1 is any data and instructions entered into the memory.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Input',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Information')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Output')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Objection')

insert into q(q_act,qname) values(@actid,'(True or False) A shortcut icon puts the actual file, folder, or app on the desktop, removing it from the location where it is saved on your computer or device')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) CAPS LOCK is a sticky key.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'The blank 1 window is the window you are currently using, which appears in front of any other open windows.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'active',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'forward')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'native')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'default')

insert into q(q_act,qname) values(@actid,'(True or False) When you move a file to the Recycle Bin or Trash, it is permanently deleted.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Which of the following units measure millions of bytes of data?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'kilobytes')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'megabytes',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'gigabytes')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'terabytes')

insert into q(q_act,qname) values(@actid,'(True or False) When you work on a file using a web app, changes are saved as you make them.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'(True or False) File properties are the same no matter what type of file.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'What is the temporary Windows storage area that holds items you copy or cut called?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the cloud')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the buffer')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the Library')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the Clipboard',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) Moving or copying a folder affects all of the contents of the folder.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'(True or False) When you open the file manager you have access to frequently or recently opened files and folders, favorite files and folders, and the main folders on your computer or device.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into act(act_cat,actname) values(@catid,'Module 5. Software and Apps Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'You want to share information about an upcoming event at your school by creating a short promotional video. Which type of app might you use to create the video?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'graphics and media',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'communications')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'device management')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'personal interest')

insert into q(q_act,qname) values(@actid,'Which of these is not an option for formatting text?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'changing the text’s color')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'changing the text’s size')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'making text bold')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'copying a region of text',@correct)

insert into q(q_act,qname) values(@actid,'Which type of app would most likely NOT be found included in a productivity suite?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'word processing')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'web browser',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'spreadsheet')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'presentation')

insert into q(q_act,qname) values(@actid,'To run a productivity app with most complete and advanced capabilities, you would most likely blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'download it from an app store to your smartphone')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'run a web app in a web browser')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'install and run the software on your desktop or laptop computer',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'update the app online to make sure you have the most recent version')

insert into q(q_act,qname) values(@actid,'Mobile first design is important because blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'developers must provide simplified user experiences for apps that run on small screens',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'sales of personal computers have surpassed sales of smartphones')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'developers can only write apps for one platform')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'smartphones generally have more processing power than laptops')

insert into q(q_act,qname) values(@actid,'When a value in a worksheet changes, the spreadsheet program will blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'reformat any cells whose values changed')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'recalculate any cells whose formulas depend on the value that changed',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'delete the value')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'launch a calculator for you to check the calculations')

insert into q(q_act,qname) values(@actid,'When giving a presentation, pushing one slide off the right edge of the screen as another one appears is an example of a(n) blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'transition',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'exit')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'entrance')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'animation')

insert into q(q_act,qname) values(@actid,'In a relational database, data is organized into rows of data called blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'fields')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'tables')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'records',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'views')

insert into q(q_act,qname) values(@actid,'When you take a photo with a digital camera, most likely it is saved in blank 1 format.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'TIFF')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'GIF')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'PNG')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'JPG',@correct)

insert into act(act_cat,actname) values(@catid,'Module 6. Security and Safety Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'blank 1 are attackers who want to attack computers but lack the knowledge needed to do so.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Script kiddies',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Hactivists')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Cyberterrorists')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Nation state actors')

insert into q(q_act,qname) values(@actid,'Each of the following is a factor that causes repetitive strain injury (RSI) except blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'repetitive activity')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'improper technique')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'lack of restful sleep',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'uninterrupted intensity')

insert into q(q_act,qname) values(@actid,'(True or False) A worm is a malicious program that uses a computer network to replicate.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'A blank 1 is a very short duration of a voltage increase that can be absorbed by a surge protector.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'spike',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'surge')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'blackout')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'brownout')

insert into q(q_act,qname) values(@actid,'(True or False) Wi-Fi Protected Access 2 (WPA2) Personal encrypts wireless data transmissions and limits who can access the Wi-Fi network.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'When creating a strong password blank 1 is the most important element.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'length',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'complexity')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'repetitiveness')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'ability to memorize')

insert into q(q_act,qname) values(@actid,'blank 1 is the process of “scrambling” information in such a way that it cannot be read unless the user possesses the “key.”')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Decryption')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Encryption',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Digital signing')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Certification')

insert into q(q_act,qname) values(@actid,'(True or False) You have the right to see your credit information.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'Which of the following is not a web browser setting for managing cookies?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Have all cookies automatically expire after 45 days.',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Accept or deny cookies.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Delete all cookies when the web browser is closed.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Make exceptions for specific websites.')

insert into act(act_cat,actname) values(@catid,'Module 7. Digital Media Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'A _______ is an image you can see, store, and manipulate on a digital device.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'geotag')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'sound wave')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'digital graphic',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'digital assistant')

insert into q(q_act,qname) values(@actid,'A process called _______ converts analog sound waves into digital sound.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'sampling',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'augmenting')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'in-betweening')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'simulating')

insert into q(q_act,qname) values(@actid,'_______ refers to the clarity or sharpness of an image.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Compression')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Bit rate')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'In-betweening')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Resolution',@correct)

insert into q(q_act,qname) values(@actid,'A(n) _______ file uses lossy compression, which discards some of the original file data during compression.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'SVG')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'GIF')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'WAV')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'JPG or JPEG',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) Of the two types of digital animation, 2-D animation is considered superior to 3-D animation.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Mobile games were the first to popularize _______, which uses an image of an actual place or thing and adds digital information to it.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'virtual reality (VR)')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'augmented reality (AR)',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'mixed reality (MR)')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'computer-aided design (CAD)')

insert into q(q_act,qname) values(@actid,'A _______ is a sophisticated computer animation useful for training and teaching in many fields.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'keyframe')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'transition')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'simulation',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'motion-sensing game')

insert into q(q_act,qname) values(@actid,'With a search engine, you can use a _______ to search for pictures that you can use, share, or modify for personal or commercial use.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'codec')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'license filter',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'graphics tablet')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'pixel')

insert into q(q_act,qname) values(@actid,'What type of software do engineers and scientists use to create wireframe drawings of objects, which they can rotate to view from many angles?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'animation software')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'photo-editing software')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'spatial recognition software')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'3-D CAD software',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) When you stream digital media, you must transfer the entire video or audio file to your computer.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) A scanner converts a printed document into a bitmap file by dividing the image into a grid of tiny cells and assigning colors to each cell.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'A _______ combines speakers and a microphone into one device.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'camcorder')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'hologram')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'headset',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'sound card')

insert into q(q_act,qname) values(@actid,'(True or False) Of all types of digital media, digital video files are the smallest and download faster than the other types.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Most _______ shows media on a timeline with separate tracks for video and sound.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'image editing software')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'stock photo galleries')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'video editing software',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'video consoles')

insert into act(act_cat,actname) values(@catid,'Module 8. Program and App Use and Development Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'(True or False) A copyright is an originator’s exclusive legal right to reproduce, publish, or sell intellectual property.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'______ refers to a program that is copyrighted and provided at no cost, but the developer retains all rights to the product.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Shareware')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Freeware',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Open source')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Public domain')

insert into q(q_act,qname) values(@actid,'(True or False) On a desktop or laptop computer, you should uninstall a program or app by using your system’s file management program to delete the folder containing the program’s files.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'A(n) ______ is an upgrade that addresses a single issue.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'patch',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'service pack')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'update')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'debugger')

insert into q(q_act,qname) values(@actid,'(True or False) Preinstalled programs and apps may be included as part of a marketing agreement between the device’s manufacturer and a software development company.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'(True or False) Programs only are considered restricted by copyright laws if the author has applied for legal protections.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Which of the following troubleshooting tools would you use if you made an update that seems to have caused issues?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'process manager')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'auditing tools')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'patch finder')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'restorer',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) An EULA grants permission for one installation.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'In OOP, a(n) ______ defines the format of an object and the actions the object can perform.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'class',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'compiler')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'interpreter')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'source')

insert into q(q_act,qname) values(@actid,'Which of the following types of software creates a personal security zone around your computer or device?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'moat')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'firewall',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'protection area')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'hacker')

insert into q(q_act,qname) values(@actid,'(True or False) UX refers to the focus on the user’s reaction and interaction to a product, including its efficiency, effectiveness, and ease of use.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'During which phase of the SDLC does the feasibility study take place?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'planning',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'design')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'analysis')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'implementation')

insert into q(q_act,qname) values(@actid,'(True or False) The waterfall method is an example of agile development.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Ruby and SQL are examples of what type of language?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'procedural')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'4GL',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'assembly')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'machine')

insert into q(q_act,qname) values(@actid,'(True or False) In order to run a program’s source code, it must be translated into machine language.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into act(act_cat,actname) values(@catid,'Module 9. Web Development Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'When you write HTML code, you use blank 1 to describe the structure of information on a webpage.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a web address')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'tags',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'styles')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'links')

insert into q(q_act,qname) values(@actid,'CSS lets you change the blank 1 of a website.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'behavior')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'structure')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'speed')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'appearance',@correct)

insert into q(q_act,qname) values(@actid,'Which of these is a use for JavaScript on a webpage?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'centering text on a page')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'displaying a slideshow of images',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'creating a hyperlink')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'displaying an image as the background of a webpage')

insert into q(q_act,qname) values(@actid,'Which of these is most likely an example of a static website?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a website for purchasing an airplane ticket')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a website for making reservations at a local restaurant')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a website for creating and sharing vacation photos')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a website for learning about a local barbershop’s hours and services',@correct)

insert into q(q_act,qname) values(@actid,'If you want to make a personal website and do not have any coding skills, you should probably use blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'an IDE')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a CMS')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Filezilla')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'a website builder',@correct)

insert into q(q_act,qname) values(@actid,'A web host’s uptime is a measure of blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'reliability, so visitors can access your site without concerns that the web server is unavailable',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'data transfer speed available so your site will load quickly')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'processing power available so complex database queries will run efficiently')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the speed of the solid-state drives on the web server, so information can be stored quickly')

insert into q(q_act,qname) values(@actid,'Which of these usually is NOT collected by a website analytics tool?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'number of visitors online')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'names of website visitors',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'how long a visitor stays on each page on average')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'type of device used to view the page')

insert into q(q_act,qname) values(@actid,'Which of these statements is true about XML?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You can export data from a database into XML to share with other applications',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You can display XML data in a browser without special formatting')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'XML data is stored in binary, so it has small file sizes')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Every XML file has a head and a body section.')

insert into q(q_act,qname) values(@actid,'When you upload webpage files from your computer to a web server, you should use a(n) blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'text editor')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'website analytics tool')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'webpage builder')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'FTP client',@correct)

insert into q(q_act,qname) values(@actid,'Code to specify webpage elements such as paragraphs, lists, links, audio or video files, is an example of blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'HTML',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'CSS')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'JavaScript')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'XML')

insert into q(q_act,qname) values(@actid,'Code to modify the background color of text or a webpage probably is an example of blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'HTML')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'CSS',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'JavaScript')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'XML')

insert into q(q_act,qname) values(@actid,'When you can click a button on a website to run code to change the font size, the code that changes the font size dynamically probably is an example of blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'HTML')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'CSS')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'JavaScript',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'XML')

insert into q(q_act,qname) values(@actid,'Which of these tags is not specified in the <body> section of a webpage?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'<title>',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'<h1>')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'<p>')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'<br>')

insert into q(q_act,qname) values(@actid,'When coding an image, HTML 5 requires you to blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'specify height and width attributes')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'specify descriptive alternative information using the alt attribute',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'place the image in an images folder')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'use the <image> tag')

insert into q(q_act,qname) values(@actid,'When coding a hyperlink to a webpage that is external to your website, an accepted behavior is to blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'open the page in the same browser tab')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'open the page in a new browser tab',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'use a relative webpage reference')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'display a warning that you are visiting a webpage outside of your website')

insert into q(q_act,qname) values(@actid,'If your webpage contains a link to an external website and its web address changes, blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'your webpage will automatically forward to the new address of the external page')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the external website’s web host will notify you to update your webpage')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the link to the external website must be a relative reference')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'the link on your website will no longer work',@correct)

insert into q(q_act,qname) values(@actid,'Which of these should you NOT do when including a video from YouTube on your website?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'copy and paste in the embed code from YouTube into your webpage’s HTML file')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'use the <video> tag to access the video in your webpage’s HTML file',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'locate the code to include the video by clicking Share then embed')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'decide whether or not to display player controls on your webpage')

insert into q(q_act,qname) values(@actid,'Older HTML tags that have been replaced with newer ways to accomplish the same task are called blank 1.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'discontinued')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'depreciated')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'deprecated',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'defunct')

insert into act(act_cat,actname) values(@catid,'Module 10. Networking Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'(True or False) Networks allow computers to share resources, such as hardware, software, data, and information.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'(True or False) A switch is a communications device that connects a communications channel such as the Internet to a sending or receiving device such as a computer.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) A DSL modem uses existing standard copper telephone wiring to send and receive digital data.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'Which of the following is not a common network topology?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'bus network')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'star network')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'client/server network',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'mesh network')

insert into q(q_act,qname) values(@actid,'Which of the following is a private network used by organizations to communicate internally?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'intranet',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Internet')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'extranet')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'virtual network')

insert into q(q_act,qname) values(@actid,'(True or False) Adware tracks and transmits personal information from your computer or device without your knowledge.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'Which of the following describes a normal-looking, yet fraudulent Wi-Fi network?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'virtual private network')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'trojan')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'spoof')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'evil twin',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) Two types of firewalls include hardware firewalls and software firewalls.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'Which of the following is an advisable practice for securing data stored on a network?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Store all data on network attached storage.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Allow all network users access to all data.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Only grant access to data to those with a legitimate need.',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Store data on a separate storage device instead of one that is connected to the network.')

insert into q(q_act,qname) values(@actid,'(True or False) Encryption converts unrecognizable data into recognizable data.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Which government agency is responsible for releasing the rules surrounding Internet access?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Federal Communications Commission (FCC)',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Internet Advisory Board (IAB)')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Internet Access Commission (IAC)')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'None of the above')

insert into q(q_act,qname) values(@actid,'(True or False) The Ethernet standard controls how network interface cards (NICs), routers, and modems share access to cables and phone lines, as well as dictates how to transmit data.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'Which of the following is not a safety precaution for securing a wireless network?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Regularly change the wireless network key.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Change the administrative password from the factory-provided default.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Disable WPA2.',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Regularly check for and perform updates to your router’s software.')

insert into act(act_cat,actname) values(@catid,'Module 11. Digital Communication Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'The sending of data from one computer or mobile device to another, often via the Internet, is called ________.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'anonymous messaging')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'networking')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'digital communication',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'netiquette')

insert into q(q_act,qname) values(@actid,'(True or False) You can send text messages over cellular networks using a mobile phone, or through the web using a desktop computer.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'A town might inform its residents of an impending tornado using a(n) ________.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'podcast')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'aggregator')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'media-sharing network')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'microblog',@correct)

insert into q(q_act,qname) values(@actid,'To remove older email messages from your mailbox without deleting them, you can _____ them.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'attach')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'reply to')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'copy')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'archive',@correct)

insert into q(q_act,qname) values(@actid,'As you use digital communication, you should follow the rules of _____ to protect yourself, your family, and your career.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'netiquette',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'interactivity')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'social media')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'privacy')

insert into q(q_act,qname) values(@actid,'Which of the following is not a negative effect of social networking?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'exposure to illegal activities')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'increased sense of community',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'loss of information control')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'decreased employability')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Pinterest, Fancred, and Fitocracy are examples of _____ networks.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'social shopping')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'sharing economy')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'interest-based')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'blog')

insert into q(q_act,qname) values(@actid,'(True or False) Online harassment is called anonymous messaging.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'Which of the following is true for video conferences?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'They can only have two participants at one time.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'They may require you to download software and set up an account.',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'They are the same as video chats.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'They do not allow participants to see and hear each other.')

insert into act(act_cat,actname) values(@catid,'Module 12. Digital Transformation: Cloud, E-commerce, and AI Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'What characteristic of cloud technology helps minimize storage costs by allowing customers to pay only for what the resources they use?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Broad network access')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Measured service',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Resource pooling')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'On-demand self-service')

insert into q(q_act,qname) values(@actid,'Your website development team is setting up a new website for your company, and you’ve decided to host this website in a cloud service. However, in the interest of improving the website’s performance, you don’t want to have to manage underlying servers. What kind of cloud service will best meet your needs?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'SaaS')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'FWaaS')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'IaaS')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'PaaS',@correct)

insert into q(q_act,qname) values(@actid,'Which of the following is not a concern when storing sensitive files in cloud storage?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Access to data during an outage')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Compliance with state and federal laws')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Automatic scaling of services',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Third party access to data')

insert into q(q_act,qname) values(@actid,'What kind of technology can allow employees to access information about accumulated vacation days from their home computers?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'E-commerce')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Cloud',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'CRM')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'IaaS')

insert into q(q_act,qname) values(@actid,'What marketing strategy can help streamline contacts with customers and target customer interests?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'E-business')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'USP')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Omnichannel',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'C2C')

insert into q(q_act,qname) values(@actid,'What kind of e-commerce platform is best suited to support C2C transactions?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Online marketplace',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Physical store')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Internet-native store')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Online storefront')

insert into q(q_act,qname) values(@actid,'Which e-commerce job role has the most direct influence on customer satisfaction ratings?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Shipping clerk')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Customer service representative',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Marketing specialist')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Delivery truck driver')

insert into q(q_act,qname) values(@actid,'What set of standards requires retailers to encrypt customers’ payment information?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'HIPAA')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'RaaS')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'PCI DSS',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'CRM')

insert into q(q_act,qname) values(@actid,'What AI technology does a computer use to get better at playing chess?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'NLP')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'ML',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Chatbot')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'IoT')

insert into q(q_act,qname) values(@actid,'An AI system can use ________ learning processes to identify a previously unknown cause of heart disease.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'reinforcement')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'supervised')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'personalized')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'unsupervised',@correct)

insert into q(q_act,qname) values(@actid,'What technologies can be used to connect an IoT device to a local network? Choose two.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Wi-Fi',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'ANN')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Bluetooth',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Smart plug')

insert into q(q_act,qname) values(@actid,'What technology can a call center technician use to find information about a product a customer is interested in purchasing?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'RPA')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Data analytics',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'IoT')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Chatbot')

insert into q(q_act,qname) values(@actid,'How can your smartphone’s virtual assistant determine if you’re giving it a command or if someone else is talking instead?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You pause before asking your question.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You use the correct wake word.',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You include details in your request.')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'You complete the voice training process.')

insert into act(act_cat,actname) values(@catid,'Module 13. Databases Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'In a veterinarian’s database, data about an individual pet is stored as a separate _____________.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'table')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'column')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'field')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'record',@correct)

insert into q(q_act,qname) values(@actid,'Aimee works for a martial arts studio. Which of the following tables will give her contact information for the mother of a student who requested more information about a new class being offered?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Classes')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Locations')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Instructors')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Students',@correct)

insert into q(q_act,qname) values(@actid,'Carlos’s small start-up company can’t afford their own servers, but they need a robust database for their new web app. Which of the following is the best fit for Carlos’s needs?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Microsoft SQL Server')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Google Docs')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Amazon Aurora',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Microsoft Excel')

insert into q(q_act,qname) values(@actid,'Chantelle wants to change the color scheme for her company’s web app, and she needs to get the logos updated. What kind of developer should she talk to?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Back-end')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'DBA')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Front-end',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Mobile')

insert into q(q_act,qname) values(@actid,'Which data type would be best for a username field?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Short text',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Hyperlink')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Long text')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'AutoNumber')

insert into q(q_act,qname) values(@actid,'Which database object is best suited to print and hand out during a presentation to a board of advisors?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Table')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Report',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Form')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Query')

insert into q(q_act,qname) values(@actid,'Which SQL statement would show the type of pet most preferred by retirees?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'INSERT INTO TblPets (Owner, Species) VALUES (‘Retired’, ‘Pet’)')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'SELECT OwnerAge FROM TblOwner WHERE OwnerAge >64')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'SELECT Species FROM TblPets WHERE OwnerAge >64')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'SELECT Species FROM TblOwners WHERE Pet=‘Yes’')

insert into q(q_act,qname) values(@actid,'Which of the following techniques would be detrimental to the security of an insurance company’s database?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Require long account passwords')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Encrypt customer contact information')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Install the database server behind a firewall')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Allow any user to delete tables',@correct)

insert into q(q_act,qname) values(@actid,'Which aspect of the CIA triad requires that passwords in a database be encrypted?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Integrity')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Scalability')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Availability')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Confidentiality',@correct)

insert into q(q_act,qname) values(@actid,'What’s the most important reason that Big Data is often managed in a cloud environment?')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Volume',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Veracity')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Value')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Variety')

insert into q(q_act,qname) values(@actid,'A database for a website where thousands of users will post their own photos needs to be highly ________________ to handle the quickly increasing number of files.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'available')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'scalable',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'consistent')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'distributed')

insert into q(q_act,qname) values(@actid,'Nadine can check her _____________ for updated, at-a-glance information on current stock prices.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'data warehouse')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'relational database')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'dashboard',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'data lake')

insert into act(act_cat,actname) values(@catid,'Module 14. Digital Ethics and Lifestyle Review Questions')
select @actid=scope_identity()

insert into q(q_act,qname) values(@actid,'(True or False) A person living a digital lifestyle relies on technology to be productive and creative, to manage activities, and to consume entertainment.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'AUP stands for ______ use policy.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'activity')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'acceptable',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'app')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'administrative')

insert into q(q_act,qname) values(@actid,'(True or False) Catfishing is the deliberate posting of content intended to cause harm or mislead people by tricking them into believing something that is false.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'(True or False) Digital inclusion is the movement to ensure that all users have access to devices, data, and infrastructure to receive high-speed, accurate, reliable information.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'The ______ allows you to use a sentence or paragraph of text without permission if you include a citation to the original source.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'Creative Commons')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'public domain')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'fair use doctrine',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'DRM')

insert into q(q_act,qname) values(@actid,'(True or False) Your digital footprint includes all of the information about you that exists online.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False')

insert into q(q_act,qname) values(@actid,'A ______ is a collaborative website where users can publish and modify content on a webpage.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'wiki',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'wireframe')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'blog')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'chat room')

insert into q(q_act,qname) values(@actid,'(True or False) It does not matter if your webpage content follows a logical order, as screen readers will read in a random order.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)

insert into q(q_act,qname) values(@actid,'A digital ______ is a period of time during which an individual refrains from using technology.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'divide')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'quarantine')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'vacation')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'detox',@correct)

insert into q(q_act,qname) values(@actid,'RSI stands for repetitive ______ injuries.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'soreness')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'strain',@correct)
insert into ans(ans_q,ansname,ans_cat) values(@qid,'syndrome')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'symptom')

insert into q(q_act,qname) values(@actid,'(True or False) It is not necessary to remove your personal data from a device before recycling or disposing of it.')
select @qid=scope_identity()
insert into ans(ans_q,ansname,ans_cat) values(@qid,'True')
insert into ans(ans_q,ansname,ans_cat) values(@qid,'False',@correct)
