declare @speciesid int

select @speciesid=speciesid
from species
where speciesname='Canis familiaris'

if @speciesid is null
	throw 50000,'Canis familiaris was not found in species',1

insert into breed(breed_species,breedname,breedFCI,breedAKC) values
	 (@speciesid,N'Affenpinscher',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Toy Group')
	,(@speciesid,N'Afghan Hound',N'Group 10: Sighthounds',N'Hound Group')
	,(@speciesid,N'Aidi',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Airedale Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Akbash',NULL,NULL)
	,(@speciesid,N'Akita (American)',N'Group 5: Spitz and primitive types',N'Working Group')
	,(@speciesid,N'Akita (Japanese)',N'Group 5: Spitz and primitive types',N'Miscellaneous Class')
	,(@speciesid,N'Alapaha Blue Blood Bulldog',NULL,NULL)
	,(@speciesid,N'Alaskan Klee Kai',NULL,N'Miscellaneous Class')
	,(@speciesid,N'Alaskan Malamute',N'Group 5: Spitz and primitive types',N'Working Group')
	,(@speciesid,N'Alpine Dachsbracke',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'American Bulldog',NULL,N'Foundation Stock Services')
	,(@speciesid,N'American English Coonhound',NULL,N'Hound Group')
	,(@speciesid,N'American Eskimo Dog (Miniature)',NULL,NULL)
	,(@speciesid,N'American Eskimo Dog (Standard)',NULL,N'Non-Sporting Group')
	,(@speciesid,N'American Eskimo Dog (Toy)',NULL,NULL)
	,(@speciesid,N'American Foxhound',N'Group 6: Scent hounds and related breeds',N'Hound Group')
	,(@speciesid,N'American Hairless Terrier',NULL,N'Terrier Group')
	,(@speciesid,N'American Leopard Hound',NULL,N'Foundation Stock Services')
	,(@speciesid,N'American Pit Bull Terrier',NULL,NULL)
	,(@speciesid,N'American Staffordshire Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'American Water Spaniel',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Anatolian Shepherd Dog',NULL,N'Working Group')
	,(@speciesid,N'Anglo-Français de Moyen Venerie',NULL,NULL)
	,(@speciesid,N'Anglo-Français de Petite Venerie',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Appenzeller Sennenhunde',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Ariegeois',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Australian Cattle Dog',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Australian Kelpie',N'Group 1: Sheepdogs and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Australian Shepherd',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Australian Stumpy Tail Cattle Dog',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Australian Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Austrian Black and Tan Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Austrian Pinscher',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Azawakh',NULL,N'Hound Group')
	,(@speciesid,N'Barak',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Barbet',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Basenji',N'Group 5: Spitz and primitive types',N'Hound Group')
	,(@speciesid,N'Basset Artesien Normand',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Basset Bley de Gascogne',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Basset Fauve de Bretagne',N'Group 6: Scent hounds and related breeds',N'Working Group')
	,(@speciesid,N'Basset Hound',N'Group 6: Scent hounds and related breeds',N'Hound Group')
	,(@speciesid,N'Bavarian Mountain Hound',N'Group 6: Scent hounds and related breeds',N'Foundation Stock Services')
	,(@speciesid,N'Beagle',N'Group 6: Scent hounds and related breeds',N'Hound Group')
	,(@speciesid,N'Beagle Harrier',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Bearded Collie',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Beauceron',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Bedlington Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Belgian Laekenois',NULL,N'Herding Group')
	,(@speciesid,N'Belgian Malinois',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Belgian Sheepdog',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Belgian Tervuren',NULL,N'Herding Group')
	,(@speciesid,N'Bergamasco',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Berger Blanc Suisse',N'Group 1: Sheepdogs and Cattledogs',NULL)
	,(@speciesid,N'Berger Picard',NULL,N'Herding Group')
	,(@speciesid,N'Bernese Mountain Dog',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Bichon Frisé',N'Group 9: Companion and Toy Dogs',N'Non-Sporting Group')
	,(@speciesid,N'Biewer Terrier',NULL,N'Toy Group')
	,(@speciesid,N'Billy',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Black Mouth Cur',NULL,NULL)
	,(@speciesid,N'Black Russian Terrier',NULL,NULL)
	,(@speciesid,N'Black and Tan Coonhound',N'Group 6: Scent hounds and related breeds',N'Hound Group')
	,(@speciesid,N'Bloodhound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Bluetick Coonhound',NULL,NULL)
	,(@speciesid,N'Boerboel',N'Working Group',NULL)
	,(@speciesid,N'Bolognese',N'Group 9: Companion and Toy Dogs',N'Miscellaneous Class')
	,(@speciesid,N'Border Collie',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Border Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Borzoi',NULL,N'Hound Group')
	,(@speciesid,N'Boston Terrier',N'Group 9: Companion and Toy Dogs',N'Non-Sporting Group')
	,(@speciesid,N'Bouvier des Ardennes',NULL,NULL)
	,(@speciesid,N'Bouvier des Flandres',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Boxer',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Boykin Spaniel',NULL,N'Sporting Group')
	,(@speciesid,N'Bracco Italiano',NULL,N'Sporting Group')
	,(@speciesid,N'Braque Francais Pyrenean',N'Group 7: Pointing Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Braque Saint-Germain',N'Group 7: Pointing Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Braque d''Auvergne',N'Group 7: Pointing Dogs',NULL)
	,(@speciesid,N'Braque de l''Ariege',NULL,NULL)
	,(@speciesid,N'Braque du Bourbonnais',N'Group 7: Pointing Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Briard',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Briquette Griffon Vendeen',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Brittany (American)',NULL,N'Sporting Group')
	,(@speciesid,N'Brittany (French)',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'Broholmer (Danish Broholmer)',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Brussels Griffon',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Bull Terrier',NULL,N'Terrier Group')
	,(@speciesid,N'Bulldog',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Non-Sporting Group')
	,(@speciesid,N'Bullmastiff',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'CIobanesc Romanesc Mioritic',N'Group 1: Sheepdogs and Cattledogs',NULL)
	,(@speciesid,N'Ca de Bestiar',NULL,NULL)
	,(@speciesid,N'Cairn Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Canaan Dog',N'Group 5: Spitz and primitive types',N'Herding Group')
	,(@speciesid,N'Canadian Eskimo Dog',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'Cane Corso',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Cardigan Welsh Corgi',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Carolina Dog',NULL,NULL)
	,(@speciesid,N'Catahoula Leopard Dog',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Catalonian Sheepdog',N'Group 1: Sheepdogs and Cattledogs',NULL)
	,(@speciesid,N'Caucasian Ovcharka',NULL,NULL)
	,(@speciesid,N'Cavalier King Charles Spaniel',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Central Asian Shepherd Dog',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Cesky Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Chart Polski',N'Group 10: Sighthounds',NULL)
	,(@speciesid,N'Chesapeake Bay Retriever',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Chien Français Blanc Tricolore',NULL,NULL)
	,(@speciesid,N'Chien Français Blanc et Noir',NULL,NULL)
	,(@speciesid,N'Chien Français Blanc et Orange',NULL,NULL)
	,(@speciesid,N'Chien d''Artois',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Chihuahua',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Chinese Crested Dog',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Chinese Shar Pei',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Non-Sporting Group')
	,(@speciesid,N'Chinook',NULL,N'Working Group')
	,(@speciesid,N'Chow Chow',N'Group 5: Spitz and primitive types',N'Non-Sporting Group')
	,(@speciesid,N'Cimarron Uruguayo',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Ciobanesc Romanesc Carpatin',N'Group 1: Sheepdogs and Cattledogs',NULL)
	,(@speciesid,N'Cirneco dell''Etna',N'Group 5: Spitz and primitive types',N'Hound Group')
	,(@speciesid,N'Clumber Spaniel',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Cocker Spaniel (American)',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Collie (Rough/Smooth)',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Coton de Tulear',N'Group 9: Companion and Toy Dogs',N'Non-Sporting Group')
	,(@speciesid,N'Crnogorski Planinski Gonic (Montenegrin Mountain Hound)',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Croatian Sheepdog',N'Group 1: Sheepdogs and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Curly-Coated Retriever',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Czechoslovakian Vlcak',N'Group 1: Sheepdogs and Cattledogs',N'Miscellaneous Class')
	,(@speciesid,N'Cão Fila de São Miguel',NULL,NULL)
	,(@speciesid,N'Cão de Castro Laboreiro',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Dachshund (Longhaired/Smooth/Wirehaired)',N'Group 4: Dachshunds',N'Hound Group')
	,(@speciesid,N'Dachshund (Miniature)',N'Group 4: Dachshunds',NULL)
	,(@speciesid,N'Dalmatian',N'Group 6: Scent hounds and related breeds',N'Non-Sporting Group')
	,(@speciesid,N'Dandie Dinmont Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Danish-Swedish Farmdog',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Deutsche Bracke',NULL,NULL)
	,(@speciesid,N'Deutscher Wachtelhund',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Dingo',NULL,NULL)
	,(@speciesid,N'Doberman Pinscher',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Dogo Argentino (Argentine Dogo)',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Dogue de Bordeaux',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Drentsche Patrijschond',N'Group 7: Pointing Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Drever',N'Group 6: Scent hounds and related breeds',N'Foundation Stock Services')
	,(@speciesid,N'Dunker',NULL,NULL)
	,(@speciesid,N'Dutch Shepherd',N'Group 1: Sheepdogs and Cattledogs',N'Miscellaneous Class')
	,(@speciesid,N'Dutch Smoushond',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'East Siberian Laika',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'English Cocker Spaniel',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'English Foxhound',N'Group 6: Scent hounds and related breeds',N'Hound Group')
	,(@speciesid,N'English Setter',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'English Shepherd',NULL,NULL)
	,(@speciesid,N'English Springer Spaniel',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'English Toy Spaniel',NULL,N'Toy Group')
	,(@speciesid,N'English Toy Terrier (Black and Tan)',N'Group 3: Terriers',NULL)
	,(@speciesid,N'Entlebucher Mountain Dog',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Herding Group')
	,(@speciesid,N'Epagneul Bleu de Picardie',N'Group 7: Pointing Dogs',NULL)
	,(@speciesid,N'Epagneul Picard',N'Group 7: Pointing Dogs',NULL)
	,(@speciesid,N'Epagneul Pont-Audemer',N'Group 7: Pointing Dogs',NULL)
	,(@speciesid,N'Estonian Hound',NULL,NULL)
	,(@speciesid,N'Estrela Mountain Dog',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Eurasier',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Field Spaniel',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Fila Brasileiro',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Finnish Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Finnish Lapphund',N'Group 5: Spitz and primitive types',N'Herding Group')
	,(@speciesid,N'Finnish Spitz',N'Group 5: Spitz and primitive types',N'Non-Sporting Group')
	,(@speciesid,N'Flat-Coated Retriever',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',NULL)
	,(@speciesid,N'French Bulldog',N'Group 9: Companion and Toy Dogs',N'Non-Sporting Group')
	,(@speciesid,N'French Spaniel',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Frisian Water Dog',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',NULL)
	,(@speciesid,N'German Longhaird Pointer',N'Group 7: Pointing Dogs',N'Foundation Stock Services')
	,(@speciesid,N'German Pinscher',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'German Rough-Haired Pointer',NULL,NULL)
	,(@speciesid,N'German Shepherd Dog',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'German Shorthaired Pointer',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'German Spitz',N'Group 5: Spitz and primitive types',N'Miscellaneous Class')
	,(@speciesid,N'German Wirehaired Pointer',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'Giant Schnauzer',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Glen of Imaal Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Golden Retriever',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Gordon Setter',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'GoÅ„czy polski',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Grand Anglo-Français Blanc et Noir',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Grand Anglo-Français Blanc et Orange',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Grand Anglo-Français Tricolore',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Grand Basset Griffon Vendeen',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Grand Bleu de Gascogne',NULL,NULL)
	,(@speciesid,N'Grand Gascon-Saintongeois',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Grand Griffon Vendeen',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Great Dane',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Great Pyrenees',NULL,N'Working Group')
	,(@speciesid,N'Greater Swiss Mountain Dog',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Greenland Dog',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'Greyhound',N'Group 10: Sighthounds',N'Hound Group')
	,(@speciesid,N'Griffon Belge',N'Group 9: Companion and Toy Dogs',NULL)
	,(@speciesid,N'Griffon Bleu de Gascogne',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Griffon Fauve de Bretagne',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Griffon Nivernais',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Haldenstovare',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Hamiltonstovare',N'Group 6: Scent hounds and related breeds',N'Foundation Stock Services')
	,(@speciesid,N'Hanoverian Hound',N'Group 6: Scent hounds and related breeds',N'Foundation Stock Services')
	,(@speciesid,N'Harrier',N'Group 6: Scent hounds and related breeds',N'Hound Group')
	,(@speciesid,N'Havanese',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Hellenic Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Hokkaido',N'Group 5: Spitz and primitive types',N'Foundation Stock Services')
	,(@speciesid,N'Hovawart',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Hungarian Greyhound',N'Group 10: Sighthounds',NULL)
	,(@speciesid,N'Hygen Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Ibizan Hound',NULL,N'Hound Group')
	,(@speciesid,N'Icelandic Sheepdog',N'Group 5: Spitz and primitive types',N'Herding Group')
	,(@speciesid,N'Irish Red and White Setter',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'Irish Setter',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'Irish Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Irish Water Spaniel',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Irish Wolfhound',N'Group 10: Sighthounds',N'Hound Group')
	,(@speciesid,N'Istrian Coarse-Haired Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Istrian Short-Haired Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Italian Greyhound',NULL,N'Toy Group')
	,(@speciesid,N'Italian Hound, Coarsehaired',NULL,NULL)
	,(@speciesid,N'Italian Hound, Shorthaired',NULL,NULL)
	,(@speciesid,N'Jack Russell Terrier',N'Group 3: Terriers',NULL)
	,(@speciesid,N'Jagdterrier',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Japanese Chin',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Japanese Spitz',N'Group 5: Spitz and primitive types',N'Foundation Stock Services')
	,(@speciesid,N'Japanese Terrier',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Jindo',N'Group 5: Spitz and primitive types',N'Foundation Stock Services')
	,(@speciesid,N'Kai Ken',N'Group 5: Spitz and primitive types',N'Miscellaneous Class')
	,(@speciesid,N'Kangal Dog',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Karelian Bear Dog',N'Group 5: Spitz and primitive types',N'Foundation Stock Services')
	,(@speciesid,N'Keeshond',N'Group 5: Spitz and primitive types',N'Non-Sporting Group')
	,(@speciesid,N'Kerry Blue Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'King Shepherd',NULL,NULL)
	,(@speciesid,N'Kishu Ken',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'Komondor',N'Group 1: Sheepdogs and Cattledogs',N'Working Group')
	,(@speciesid,N'Kooikerhondji',NULL,NULL)
	,(@speciesid,N'Krasky Ovcar',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Kromfohrlander',N'Group 9: Companion and Toy Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Kuvasz',N'Group 1: Sheepdogs and Cattledogs',N'Working Group')
	,(@speciesid,N'Kyi-Leo',NULL,NULL)
	,(@speciesid,N'Labrador Retriever',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Lagotto Romagnolo',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Lakeland Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Lancashire Heeler',NULL,N'Herding Group')
	,(@speciesid,N'Landseer',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Lapinporokoira',NULL,NULL)
	,(@speciesid,N'Large Münsterländer',N'Group 7: Pointing Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Leonberger',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Lhasa Apso',N'Group 9: Companion and Toy Dogs',N'Non-Sporting Group')
	,(@speciesid,N'Löwchen',NULL,N'Non-Sporting Group')
	,(@speciesid,N'Majorca Mastiff',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Maltese',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Manchester Terrier (Standard)',N'Group 3: Terriers',NULL)
	,(@speciesid,N'Manchester Terrier (Toy)',N'Group 3: Terriers',N'Toy Group')
	,(@speciesid,N'Maremma Sheepdog',N'Group 1: Sheepdogs and Cattledogs',NULL)
	,(@speciesid,N'Mastiff',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Mi-Ki',NULL,NULL)
	,(@speciesid,N'Mini-Pei',NULL,NULL)
	,(@speciesid,N'Miniature American Shepherd',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Miniature Australian Shepherd',NULL,NULL)
	,(@speciesid,N'Miniature Bull Terrier',NULL,N'Terrier Group')
	,(@speciesid,N'Miniature Pinscher',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Toy Group')
	,(@speciesid,N'Miniature Schnauzer',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Terrier Group')
	,(@speciesid,N'Mountain Cur',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Mudi',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Neapolitan Mastiff',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Nederlandse Kooikerhondje',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'New Guinea Singing Dog',NULL,NULL)
	,(@speciesid,N'Newfoundland',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Norfolk Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Norrbottenspets',N'Group 5: Spitz and primitive types',N'Miscellaneous Class')
	,(@speciesid,N'Norwegian Buhund',N'Group 5: Spitz and primitive types',N'Herding Group')
	,(@speciesid,N'Norwegian Elkhound',N'Group 5: Spitz and primitive types',N'Hound Group')
	,(@speciesid,N'Norwegian Lundehund',N'Group 5: Spitz and primitive types',N'Non-Sporting Group')
	,(@speciesid,N'Norwich Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Nova Scotia Duck-Tolling Retriever',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Old Danish Bird Dog',N'Group 7: Pointing Dogs',NULL)
	,(@speciesid,N'Old English Sheepdog',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Olde English Bulldogge',NULL,NULL)
	,(@speciesid,N'Otterhound',N'Group 6: Scent hounds and related breeds',N'Hound Group')
	,(@speciesid,N'Owczarek Podhalanski (Polish Mountain Sheepdog)',NULL,NULL)
	,(@speciesid,N'Papillon',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Parson Russell Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Patterdale Terrier',NULL,NULL)
	,(@speciesid,N'Pekingese',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Pembroke Welsh Corgi',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Perdiguero de Burgos',N'Group 7: Pointing Dogs',NULL)
	,(@speciesid,N'Perro de Presa Canario',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Perucian Inca Orchid',NULL,N'Miscellaneous Class')
	,(@speciesid,N'Petit Basset Griffon Vendéen',N'Group 6: Scent hounds and related breeds',N'Hound Group')
	,(@speciesid,N'Petit Bleu de Gascogne',NULL,NULL)
	,(@speciesid,N'Petit Bragançon',NULL,NULL)
	,(@speciesid,N'Petit Gascon-Saintongeois',NULL,NULL)
	,(@speciesid,N'Petit Griffon Bleu de Gascogne',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Pharaoh Hound',N'Group 5: Spitz and primitive types',N'Hound Group')
	,(@speciesid,N'Plott',NULL,N'Hound Group')
	,(@speciesid,N'Podenco Canario',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'Pointer',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'Poitevin',NULL,NULL)
	,(@speciesid,N'Polish Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Polish Lowland Sheepdog',NULL,NULL)
	,(@speciesid,N'Pomeranian',N'Group 5: Spitz and primitive types',N'Toy Group')
	,(@speciesid,N'Poodle (Medium)',N'Group 9: Companion and Toy Dogs',NULL)
	,(@speciesid,N'Poodle (Miniature)',N'Group 9: Companion and Toy Dogs',NULL)
	,(@speciesid,N'Poodle (Standard)',N'Group 9: Companion and Toy Dogs',N'Non-Sporting Group')
	,(@speciesid,N'Poodle (Toy)',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Porcelaine',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Portuguese Podengo',N'Group 5: Spitz and primitive types',N'Miscellaneous Class')
	,(@speciesid,N'Portuguese Podengo Pequeno',N'Group 5: Spitz and primitive types',N'Hound Group')
	,(@speciesid,N'Portuguese Pointer',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Portuguese Sheepdog',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Portuguese Water Dog',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Working Group')
	,(@speciesid,N'Posavaz Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Pudelpointer',N'Group 7: Pointing Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Pug',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Puli',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Pyrenean Mastiff',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',NULL)
	,(@speciesid,N'Pyrenean Shepherd',NULL,N'Herding Group')
	,(@speciesid,N'Rafeiro do Alentejo',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Rastreador Brasileiro',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Rat Terrier',NULL,NULL)
	,(@speciesid,N'Redbone Coonhound',NULL,N'Hound Group')
	,(@speciesid,N'Rhodesian Ridgeback',N'Group 6: Scent hounds and related breeds',N'Hound Group')
	,(@speciesid,N'Rottweiler',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Russell Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Russian Toy',NULL,N'Toy Group')
	,(@speciesid,N'Russian Tsvetnaya Bolonka',NULL,NULL)
	,(@speciesid,N'Russo-European Laika',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'Saarlooswolfhond',N'Group 1: Sheepdogs and Cattledogs',NULL)
	,(@speciesid,N'Sabueso Español',NULL,NULL)
	,(@speciesid,N'Saluki',N'Group 10: Sighthounds',NULL)
	,(@speciesid,N'Samoyed',N'Group 5: Spitz and primitive types',N'Working Group')
	,(@speciesid,N'Sanshu',NULL,NULL)
	,(@speciesid,N'Sarplaninac',NULL,NULL)
	,(@speciesid,N'Schapendoes',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Schiller Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Schipperke',NULL,N'Non-Sporting Group')
	,(@speciesid,N'Scottish Deerhound',N'Group 10: Sighthounds',N'Hound Group')
	,(@speciesid,N'Scottish Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Sealyham Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Serbian Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Serbian Tricolor Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Shetland Sheepdog',N'Group 1: Sheepdogs and Cattledogs',N'Herding Group')
	,(@speciesid,N'Shiba Inu',N'Group 5: Spitz and primitive types',N'Non-Sporting Group')
	,(@speciesid,N'Shih Tzu',N'Group 9: Companion and Toy Dogs',N'Toy Group')
	,(@speciesid,N'Shikoku',N'Group 5: Spitz and primitive types',N'Foundation Stock Services')
	,(@speciesid,N'Shiloh Shepherd',NULL,NULL)
	,(@speciesid,N'Siberian Husky',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'Silky Terrier',NULL,N'Toy Group')
	,(@speciesid,N'Skye Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Sloughi',N'Group 10: Sighthounds',N'Hound Group')
	,(@speciesid,N'Slovakian Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Slovakian Wire-Haired Pointing Dog',N'Group 7: Pointing Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Slovensky Cuvac',NULL,NULL)
	,(@speciesid,N'Slovensky Kopov',NULL,NULL)
	,(@speciesid,N'Smaland Hound',NULL,NULL)
	,(@speciesid,N'Small Munsterlander Pointer',NULL,N'Miscellaneous Class')
	,(@speciesid,N'Smooth Fox Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Soft-Coated Wheaten Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'South Russian Ovcharka',NULL,NULL)
	,(@speciesid,N'South Russian Steppe Hound',NULL,NULL)
	,(@speciesid,N'Spanish Greyhound',N'Group 10: Sighthounds',NULL)
	,(@speciesid,N'Spanish Mastiff',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Spanish Water Dog',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Herding Group')
	,(@speciesid,N'Spinone Italiano',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'Sporting Lucas Terrier',NULL,NULL)
	,(@speciesid,N'St. Bernard',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Stabyhoun',N'Group 7: Pointing Dogs',N'Foundation Stock Services')
	,(@speciesid,N'Staffordshire Bull Terrier',NULL,N'Terrier Group')
	,(@speciesid,N'Standard Schnauzer',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Stephens'' Cur',NULL,NULL)
	,(@speciesid,N'Stryian Coarse-Haired Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Sussex Spaniel',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Swedish Elkhound',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'Swedish Lapphund',N'Group 5: Spitz and primitive types',N'Foundation Stock Services')
	,(@speciesid,N'Swedish Vallhund',N'Group 5: Spitz and primitive types',N'Herding Group')
	,(@speciesid,N'Swiss Hound, Bernese Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Swiss Hound, Jura Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Swiss Hound, Lucerne Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Swiss Hound, Schwyz Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Swiss Hound, Small Bernese Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Swiss Hound, Small Jura Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Swiss Hound, Small Lucerne Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Swiss Hound, Small Schwyz Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Taiwan Dog',N'Group 5: Spitz and primitive types',N'Foundation Stock Services')
	,(@speciesid,N'Teddy Roosevelt Terrier',NULL,N'Miscellaneous Class')
	,(@speciesid,N'Telomian',NULL,NULL)
	,(@speciesid,N'Tenterfield Terrier',NULL,NULL)
	,(@speciesid,N'Terrier Brasileiro',NULL,NULL)
	,(@speciesid,N'Thai Ridgeback',N'Group 5: Spitz and primitive types',N'Foundation Stock Services')
	,(@speciesid,N'Tibetan Mastiff',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Working Group')
	,(@speciesid,N'Tibetan Spaniel',N'Group 9: Companion and Toy Dogs',N'Non-Sporting Group')
	,(@speciesid,N'Tibetan Terrier',N'Group 9: Companion and Toy Dogs',N'Non-Sporting Group')
	,(@speciesid,N'Tornjak',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Tosa',N'Group 2: Pinscher and Schnauzer - Molossoid and Swiss Mountain and Cattledogs',N'Foundation Stock Services')
	,(@speciesid,N'Toy Fox Terrier',NULL,N'Toy Group')
	,(@speciesid,N'Transylvanian Hound',N'Group 6: Scent hounds and related breeds',N'Foundation Stock Services')
	,(@speciesid,N'Treeing Cur',NULL,NULL)
	,(@speciesid,N'Treeing Feist',NULL,NULL)
	,(@speciesid,N'Treeing Tennessee Brindle',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Treeing Walker Coonhound',NULL,N'Hound Group')
	,(@speciesid,N'Trigg Hound',NULL,NULL)
	,(@speciesid,N'Tyrolean Hound',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Vizsla',NULL,N'Sporting Group')
	,(@speciesid,N'Volpino Italiano',N'Group 5: Spitz and primitive types',N'Foundation Stock Services')
	,(@speciesid,N'Weimaraner',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'Welsh Springer Spaniel',N'Group 8: Retrievers - Flushing Dogs - Water Dogs',N'Sporting Group')
	,(@speciesid,N'Welsh Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'West Highland White Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'West Siberian Laika',NULL,NULL)
	,(@speciesid,N'Westphalian Dachsbracke',N'Group 6: Scent hounds and related breeds',NULL)
	,(@speciesid,N'Whippet',N'Group 10: Sighthounds',N'Hound Group')
	,(@speciesid,N'White Shepherd',NULL,NULL)
	,(@speciesid,N'Wire Fox Terrier',N'Group 3: Terriers',N'Terrier Group')
	,(@speciesid,N'Wirehaired Pointing Griffon',N'Group 7: Pointing Dogs',N'Sporting Group')
	,(@speciesid,N'Wirehaired Vizsla',NULL,N'Sporting Group')
	,(@speciesid,N'Working Kelpie',NULL,N'Foundation Stock Services')
	,(@speciesid,N'Xoloitzcuintli (Miniature)',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'Xoloitzcuintli (Standard)',N'Group 5: Spitz and primitive types',N'Non-Sporting Group')
	,(@speciesid,N'Xoloitzcuintli (Toy)',N'Group 5: Spitz and primitive types',NULL)
	,(@speciesid,N'Yorkshire Terrier',N'Group 3: Terriers',N'Toy Group')
go

