
select speciesid,speciesname
from species
where speciesname like 'Capra%'
order by speciesname

declare @speciesid int=360192

insert into breed(breed_species,breedname)
select @speciesid,v.breedname
from (values
	 (N'Alpine Goats')
	,(N'Altai Mountain Goats')
	,(N'Anglo-Nubian Goats')
	,(N'Angora Goats')
	,(N'Appenzell Goats')
	,(N'Arapawa Island Goats')
	,(N'Australian Goats')
	,(N'Bagot Goats')
	,(N'Barbari Goats')
	,(N'Beetal Goats')
	,(N'Belgian Fawn Goats')
	,(N'Benadir Goats')
	,(N'Bhuj Goats')
	,(N'Boer Goats')
	,(N'Booted Goats')
	,(N'British Alpine Goats')
	,(N'Brown Shorthair Goats')
	,(N'Canary Island Goats')
	,(N'Canindé Goats')
	,(N'Cashmere Goats')
	,(N'Chapar Goats')
	,(N'Corsican Goats')
	,(N'Daera Din Panah Goats')
	,(N'Damani Goats')
	,(N'Danish Landrace Goats')
	,(N'Don Goats')
	,(N'Dutch Landrace Goats')
	,(N'Erzgebirge Goats')
	,(N'Finnish Landrace Goats')
	,(N'Golden Guernsey Goats')
	,(N'Grisons Striped Goats')
	,(N'Hailun Goats')
	,(N'Haimen Goats')
	,(N'Hasi Goats')
	,(N'Hejazi Goats')
	,(N'Hexi Cashmere Goats')
	,(N'Hongtong Goats')
	,(N'Huaipi Goats')
	,(N'Huaitoutala Goats')
	,(N'Hungarian Improved Goats')
	,(N'Irish Goats')
	,(N'Jining Grey Goats')
	,(N'Kaghani Goats')
	,(N'Kalahari Red Goats')
	,(N'Kamori Goats')
	,(N'Kiko Goats')
	,(N'Kinder Goats')
	,(N'LaMancha Goats')
	,(N'Laoshan Goats')
	,(N'Moxoto Goats')
	,(N'Murcia-Granada Goats')
	,(N'Myotonic (Wooden Leg) Goats')
	,(N'Nachi Goats')
	,(N'Nigerian Dwarf Goats')
	,(N'Norwegian Goats')
	,(N'Oberhasli Goats')
	,(N'Peacock Goats')
	,(N'Philippine Goats')
	,(N'Poitou Goats')
	,(N'Pygmy Goats')
	,(N'Pyrenean Goats')
	,(N'Qinshan Goats')
	,(N'Repartida Goats')
	,(N'Russian White and Gorki Goats')
	,(N'Saanen Goats')
	,(N'Sahelian Goats')
	,(N'San Clemente Goats')
	,(N'Savanna Goats')
	,(N'Somali Goats')
	,(N'Spanish Goats')
	,(N'SRD Goats')
	,(N'Swedish Landrace Goats')
	,(N'Thuringian Goats')
	,(N'Toggenburg Goats')
	,(N'Uzbek Black Goats')
	,(N'Valais Blackneck Goats')
	,(N'Verata Goats')
	,(N'West African Dwarf Goats')
	,(N'White Shorthair Goats')
	,(N'Xinjiang Goats')
	,(N'Xuhai Goats')
	,(N'Yemen Mountain Goats')
	,(N'Zhongwei Goats')
) v(breedname)
where not exists (
	select 1
	from breed
	where breed_species=@speciesid
	and breedname=v.breedname
)
go

