select speciesid,speciesname
from species
where speciesname like 'Gallus%'
order by speciesname


declare @speciesid int=351168

insert into breed(breed_species,breedname)
select @speciesid,v.breedname
from (values
	 (N'AC Chickens')
	,(N'Ameraucana Chickens')
	,(N'Ancona Chickens')
	,(N'Andalusian Chickens')
	,(N'Appenzell Bearded Hen Chickens')
	,(N'Appenzell Pointed Hood Hen Chickens')
	,(N'Araucana Chickens')
	,(N'Aseel Chickens')
	,(N'Australorp Chickens')
	,(N'Baheij Chickens')
	,(N'Bandara Chickens')
	,(N'Barnevelders Chickens')
	,(N'Brahma Chickens')
	,(N'Buckeye Chickens')
	,(N'Buttercup Chickens')
	,(N'Campine Chickens')
	,(N'Catalana Chickens')
	,(N'Chantecler Chickens')
	,(N'Cochin Chickens')
	,(N'Cornish Chickens')
	,(N'Crevecoeur Chickens')
	,(N'Cubalaya Chickens')
	,(N'Delaware Chickens')
	,(N'Dominiques Chickens')
	,(N'Dorking Chickens')
	,(N'Dutch Bantam Chickens')
	,(N'Faverolles Chickens')
	,(N'Friesian Chickens')
	,(N'Frizzle Chickens')
	,(N'Gimmizah Chickens')
	,(N'Golden Montazah Chickens')
	,(N'Hamburg Chickens')
	,(N'Holland Chickens')
	,(N'Houdan Chickens')
	,(N'Java Chickens')
	,(N'Jersey Giant Chickens')
	,(N'La Fleche Chickens')
	,(N'Lakenvelder Chickens')
	,(N'Lamona Chickens')
	,(N'Langshan Chickens')
	,(N'Legbar Chickens')
	,(N'Leghorn Chickens')
	,(N'Malay Chickens')
	,(N'Marans Chickens')
	,(N'Matrouh Chickens')
	,(N'Minorca Chickens')
	,(N'Modern Game Chickens')
	,(N'Naked Neck Chickens (Turken)')
	,(N'Nankin Chickens')
	,(N'New Hampshire Red Chickens')
	,(N'Old English Game Chickens')
	,(N'Orpington Chickens')
	,(N'Plymouth Rock Chickens')
	,(N'Polish Chickens')
	,(N'Red Cap Chickens')
	,(N'Rhode Island Red Chickens')
	,(N'Russian Orloff Chickens')
	,(N'Sasso Chickens')
	,(N'Sebright Chickens')
	,(N'Shamo Chickens')
	,(N'Silkie Bantam Chickens')
	,(N'Silver Montazah Chickens')
	,(N'Styrian Chickens')
	,(N'Sultan Chickens')
	,(N'Sumatra Chickens')
	,(N'Sussex Chickens')
	,(N'Swiss Hen Chickens (Schweizerhuhn)')
	,(N'Welsummer Chickens')
	,(N'White-Faced Black Spanish Chickens')
	,(N'Wyandotte Chickens')
	,(N'Yokohama Chickens')
) v(breedname)
where not exists (
	select 1
	from breed
	where breed_species=@speciesid
	and breedname=v.breedname
)
go
