-- https://breeds.okstate.edu/cattle
select speciesid,speciesname
from species
where speciesname like 'Bos%'
order by speciesname

declare @speciesid int=360216

insert into breed(breed_species,breedname)
select @speciesid,v.breedname
from (values
	 (N'Africander Cattle')
	,(N'Akaushi Cattle')
	,(N'Alberes Cattle')
	,(N'Alentejana Cattle')
	,(N'Allmogekor Cattle')
	,(N'American Braford Cattle')
	,(N'American Breed Cattle')
	,(N'American White Park Cattle')
	,(N'Amerifax Cattle')
	,(N'Amrit Mahal Cattle')
	,(N'Anatolian Black Cattle')
	,(N'Andalusian Black Cattle')
	,(N'Andalusian Grey Cattle')
	,(N'Angeln Cattle')
	,(N'Angus Cattle')
	,(N'Ankole Cattle')
	,(N'Ankole-Watusi Cattle')
	,(N'Argentine Criollo Cattle')
	,(N'Asturian Mountain Cattle')
	,(N'Asturian Valley Cattle')
	,(N'Aubrac Cattle')
	,(N'Aulie-Ata Cattle')
	,(N'Australian Braford Cattle')
	,(N'Australian Friesian Sahiwal Cattle')
	,(N'Australian Lowline Cattle')
	,(N'Australian Milking Zebu Cattle')
	,(N'Ayrshire Cattle')
	,(N'Azaouak Cattle')
	,(N'Bachaur Cattle')
	,(N'Baladi Cattle')
	,(N'Baltata Romaneasca Cattle')
	,(N'Barka Cattle')
	,(N'Barzona Cattle')
	,(N'Bazadais Cattle')
	,(N'Béarnais Cattle')
	,(N'Beefalo Cattle')
	,(N'Beefmaker Cattle')
	,(N'Beefmaster Cattle')
	,(N'Belarus Red Cattle')
	,(N'Belgian Blue Cattle')
	,(N'Belgian Red Cattle')
	,(N'Belmont Adaptaur Cattle')
	,(N'Belmont Red Cattle')
	,(N'Belted Galloway Cattle')
	,(N'Bengali Cattle')
	,(N'Berrendas Cattle')
	,(N'Bhagnari Cattle')
	,(N'Black Hereford Cattle')
	,(N'Blacksided Trondheim and Norland Cattle')
	,(N'Blanca Cacereña/White Cáceres Cattle')
	,(N'Blanco Orejinegro Cattle')
	,(N'Blonde d''Aquitaine Cattle')
	,(N'Bonsmara Cattle')
	,(N'Boran Cattle')
	,(N'Bordelais Cattle')
	,(N'Brahman Cattle')
	,(N'Brahmousin Cattle')
	,(N'Brangus Cattle')
	,(N'Braunvieh Cattle')
	,(N'British White Cattle')
	,(N'Brown Swiss Cattle')
	,(N'Busa Cattle')
	,(N'Cachena Cattle')
	,(N'Canadian Highland Cattle')
	,(N'Canadienne Cattle')
	,(N'Canary Island Cattle')
	,(N'Canchim Cattle')
	,(N'Carinthian Blond Cattle')
	,(N'Caucasian Cattle')
	,(N'Channi Cattle')
	,(N'Charbray Cattle')
	,(N'Charolais Cattle')
	,(N'Chianina Cattle')
	,(N'Chinampo Cattle')
	,(N'Chinese Black-and-White Cattle')
	,(N'Chinese Mongolian Cattle')
	,(N'Chinese Xinjiang Brown Cattle')
	,(N'Cholistani Cattle')
	,(N'Corriente Cattle')
	,(N'Costeño con Cuernos Cattle')
	,(N'Dajal Cattle')
	,(N'Damascus Cattle')
	,(N'Damietta Cattle')
	,(N'Dangi Cattle')
	,(N'Danish Jersey Cattle')
	,(N'Danish Red Cattle')
	,(N'Deoni Cattle')
	,(N'Devon Cattle')
	,(N'Dexter Cattle')
	,(N'Dhanni Cattle')
	,(N'Djali Cattle')
	,(N'Dølafe Cattle')
	,(N'Droughtmaster Cattle')
	,(N'Dulong Cattle')
	,(N'Dutch Belted (Lakenvelder) Cattle')
	,(N'Dutch Friesian Cattle')
	,(N'East Anatolian Red Cattle')
	,(N'Enderby Island Cattle')
	,(N'English Longhorn Cattle')
	,(N'Estonian Red Cattle')
	,(N'Evolène Cattle')
	,(N'Fighting Cattle')
	,(N'Finnish Cattle')
	,(N'Fjall Cattle')
	,(N'Florida Cracker Cattle')
	,(N'Galician Blond Cattle')
	,(N'Galloway Cattle')
	,(N'Gaolao Cattle')
	,(N'Gascon Cattle')
	,(N'Gelbray Cattle')
	,(N'Gelbvieh Cattle')
	,(N'German Angus Moiled Cattle')
	,(N'German Red Pied Cattle')
	,(N'Gir Cattle')
	,(N'Glan Cattle')
	,(N'Gloucester Cattle')
	,(N'Gobra Cattle')
	,(N'Greek Shorthorn Cattle')
	,(N'Greek Steppe Cattle')
	,(N'Groningen Cattle')
	,(N'Guernsey Cattle')
	,(N'Guzerat Cattle')
	,(N'Hallikar Cattle')
	,(N'Hariana Cattle')
	,(N'Harton Cattle')
	,(N'Hays Converter Cattle')
	,(N'Hereford Cattle')
	,(N'Herens Cattle')
	,(N'Highland Cattle')
	,(N'Hinterwald Cattle')
	,(N'Holando-Argentino Cattle')
	,(N'Holstein Cattle')
	,(N'Horro Cattle')
	,(N'Hungarian Grey Cattle')
	,(N'Icelandic Cattle')
	,(N'Illawarra Cattle')
	,(N'Indo-Brazilian Cattle')
	,(N'Irish Moiled Cattle')
	,(N'Israeli Holstein Cattle')
	,(N'Israeli Red Cattle')
	,(N'Istoben Cattle')
	,(N'Jamaica Black Cattle')
	,(N'Jamaica Hope Cattle')
	,(N'Jamaica Red Cattle')
	,(N'Jaulan Cattle - Jaulan')
	,(N'Jaulan Cattle - Sharabi')
	,(N'Jersey Cattle')
	,(N'Kangayam Cattle')
	,(N'Kankrej Cattle')
	,(N'Karan Fries Cattle')
	,(N'Karan Swiss Cattle')
	,(N'Kazakh Cattle')
	,(N'Kenwariya Cattle')
	,(N'Kerry Cattle')
	,(N'Kherigarh Cattle')
	,(N'Khillari Cattle')
	,(N'Kholmogory Cattle')
	,(N'Kilis Cattle')
	,(N'Krishna Valley Cattle')
	,(N'Kurdi Black Cattle')
	,(N'Kuri Cattle')
	,(N'Latvian Brown (Buraya latviiskaya) Cattle')
	,(N'Limousin Cattle')
	,(N'Limpurger Cattle')
	,(N'Lincoln Red Cattle')
	,(N'Lithuanian Red Cattle')
	,(N'Lohani Cattle')
	,(N'Lourdais Cattle')
	,(N'Luing Cattle')
	,(N'Madagascar Zebu Cattle')
	,(N'Maine-Anjou Cattle')
	,(N'Malvi Cattle')
	,(N'Mandalong Cattle')
	,(N'Marchigiana Cattle')
	,(N'Maremmana Cattle')
	,(N'Masai Cattle')
	,(N'Mashona Cattle')
	,(N'Maure Cattle')
	,(N'Mazandarani Cattle')
	,(N'Meuse-Rhine-Yssel Cattle')
	,(N'Mewati Cattle')
	,(N'Milking Devon Cattle')
	,(N'Milking Shorthorn Cattle')
	,(N'Miniature Zebu Cattle')
	,(N'Mirandesa Cattle')
	,(N'Modicana Cattle')
	,(N'Montbéliard Cattle')
	,(N'Morucha Cattle')
	,(N'Murboden Cattle')
	,(N'Murray Grey Cattle')
	,(N'Muturu - West African Dwarf Shorthorn Cattle')
	,(N'N''dama Cattle')
	,(N'Nagori Cattle')
	,(N'Nanyang Cattle')
	,(N'Nelore Cattle')
	,(N'Nguni Cattle')
	,(N'Nimari Cattle')
	,(N'Normande Cattle')
	,(N'Norwegian Red Cattle')
	,(N'Ongole Cattle')
	,(N'Orma Boran Cattle')
	,(N'Oropa Cattle')
	,(N'Ovambo Cattle')
	,(N'Parthenais Cattle')
	,(N'Philippine Native Cattle')
	,(N'Piedmontese Cattle')
	,(N'Pinzgauer Cattle')
	,(N'Polish Red Cattle')
	,(N'Polled Hereford Cattle')
	,(N'Ponwar Cattle')
	,(N'Qinchuan Cattle')
	,(N'Rath Cattle')
	,(N'Rathi Cattle')
	,(N'Rätien Gray Cattle')
	,(N'Red Angus Cattle')
	,(N'Red Brangus Cattle')
	,(N'Red Fulani or Mbororo Cattle')
	,(N'Red Pied Friesian Cattle')
	,(N'Red Poll Cattle')
	,(N'Red Polled Østland Cattle')
	,(N'Red Sindhi Cattle')
	,(N'Red Steppe Cattle')
	,(N'Reggiana Cattle')
	,(N'Retinta Cattle')
	,(N'Rojhan Cattle')
	,(N'Romagnola Cattle')
	,(N'Romosinuano Cattle')
	,(N'Russian Black Pied Cattle')
	,(N'RX3 Cattle')
	,(N'Sahiwal Cattle')
	,(N'Salers Cattle')
	,(N'Salorn Cattle')
	,(N'San Martinero Cattle')
	,(N'Sanhe Cattle')
	,(N'Santa Cruz Cattle')
	,(N'Santa Gertrudis Cattle')
	,(N'Sarabi Cattle')
	,(N'Senepol Cattle')
	,(N'Shetland Cattle')
	,(N'Shorthorn Cattle')
	,(N'Siboney Cattle')
	,(N'Simbrah Cattle')
	,(N'Simmental Cattle')
	,(N'Siri Cattle')
	,(N'Slovenian Cika Cattle')
	,(N'South Devon Cattle')
	,(N'Sudanese Fulani Cattle')
	,(N'Sussex Cattle')
	,(N'Swedish Friesian Cattle')
	,(N'Swedish Red Polled Cattle')
	,(N'Swedish Red-and-White Cattle')
	,(N'Tarentaise Cattle')
	,(N'Telemark Cattle')
	,(N'Texas Longhorn Cattle')
	,(N'Texon Cattle')
	,(N'Tharparkar Cattle')
	,(N'Tswana Cattle')
	,(N'Tuli Cattle')
	,(N'Turkish Grey Steppe Cattle')
	,(N'Ukrainian Beef Cattle')
	,(N'Ukrainian Grey Cattle')
	,(N'Ukrainian Whitehead Cattle')
	,(N'Umblachery Cattle')
	,(N'Ural Black Pied Cattle')
	,(N'Vestland Fjord Cattle')
	,(N'Vestland Red Polled Cattle')
	,(N'Vosges Cattle')
	,(N'Wagyu Cattle')
	,(N'Welsh Black Cattle')
	,(N'White Park Cattle')
	,(N'Yanbian Cattle')
) v(breedname)
where not exists (
	select 1
	from breed
	where breed_species=@speciesid
	and breedname=v.breedname
)
go
