-- https://breeds.okstate.edu/sheep

select speciesid,speciesname
from species
where speciesname like 'Ovis%'
order by speciesname


declare @speciesid int=361060

insert into breed(breed_species,breedname)
select @speciesid,v.breedname
from (values
	 (N'Acipayam Sheep')
	,(N'Adal Sheep')
	,(N'Afghan Arabi Sheep')
	,(N'Africana Sheep')
	,(N'Alai Sheep')
	,(N'Alcarrena Sheep')
	,(N'Algarve Churro Sheep')
	,(N'Algerian Arab Sheep')
	,(N'Altai Sheep')
	,(N'Altay Sheep')
	,(N'American Blackbelly Sheep')
	,(N'Apennine Sheep')
	,(N'Arabi Sheep')
	,(N'Arapawa Island Sheep')
	,(N'Awassi Sheep')
	,(N'Balkhi Sheep')
	,(N'Baluchi Sheep')
	,(N'Balwen Welsh Mountain Sheep')
	,(N'Barbados Blackbelly Sheep')
	,(N'Bavarian Forest Sheep')
	,(N'Bentheimer Landschaf Sheep')
	,(N'Bergamasca Sheep')
	,(N'Beulah Speckled-Face Sheep')
	,(N'Bibrik Sheep')
	,(N'Biellese Sheep')
	,(N'Black Welsh Mountain Sheep')
	,(N'Blackhead Persian Sheep')
	,(N'Bleu du Maine Sheep')
	,(N'Bluefaced Leicester Sheep')
	,(N'Bond Sheep')
	,(N'Booroola Merino Sheep')
	,(N'Border Leicester Sheep')
	,(N'Boreray Sheep')
	,(N'Bovska Sheep')
	,(N'Braunes Bergschaf Sheep')
	,(N'Brazilian Somali Sheep')
	,(N'Brecknock Hill Cheviot Sheep')
	,(N'Brillenschaf Sheep')
	,(N'British Milk Sheep')
	,(N'Bündner Oberland Sheep')
	,(N'California Red Sheep')
	,(N'California Variegated Mutant Sheep')
	,(N'Campanian Barbary Sheep')
	,(N'Castlemilk Moorit Sheep')
	,(N'Charollais Sheep')
	,(N'Cheviot Sheep')
	,(N'Chios Sheep')
	,(N'Cholistani Sheep')
	,(N'Clun Forest Sheep')
	,(N'Coburger Fuchsschaf Sheep')
	,(N'Columbia Sheep')
	,(N'Comeback Sheep')
	,(N'Comisana Sheep')
	,(N'Coopworth Sheep')
	,(N'Cormo Sheep')
	,(N'Corriedale Sheep')
	,(N'Cotswold Sheep')
	,(N'Criollo Sheep')
	,(N'Daglic Sheep')
	,(N'Dala Sheep')
	,(N'Dalesbred Sheep')
	,(N'Damani Sheep')
	,(N'Damara Sheep')
	,(N'Danish Landrace Sheep')
	,(N'Dartmoor Sheep')
	,(N'Debouillet Sheep')
	,(N'Delaine Merino Sheep')
	,(N'Derbyshire Gritstone Sheep')
	,(N'Deutsches Blaukoepfiges Fleischschaf Sheep')
	,(N'Devon Closewool Sheep')
	,(N'Dorper Sheep')
	,(N'Dorset Down Sheep')
	,(N'Dorset Sheep')
	,(N'Drysdale Sheep')
	,(N'Elliottdale Sheep')
	,(N'Exmoor Horn Sheep')
	,(N'Fabrianese Sheep')
	,(N'Faeroes Sheep')
	,(N'Finnsheep Sheep')
	,(N'Fonthill Merino Sheep')
	,(N'Friesian Milk Sheep')
	,(N'Galway Sheep')
	,(N'Gansu Alpine Fine-Wool Sheep')
	,(N'Gentile di Puglia Sheep')
	,(N'German Blackheaded Mutton Sheep')
	,(N'German Mountain Sheep')
	,(N'German Mutton Merino Sheep')
	,(N'German Whiteheaded Mutton Sheep')
	,(N'Gotland Sheep')
	,(N'Graue Gehoernte Heidschnucke Sheep')
	,(N'Gromark Sheep')
	,(N'Gulf Coast Native Sheep')
	,(N'Gute Sheep')
	,(N'Hampshire Sheep')
	,(N'Han Sheep')
	,(N'Harnai Sheep')
	,(N'Hasht Nagri Sheep')
	,(N'Hazaragie Sheep')
	,(N'Hebridean Sheep')
	,(N'Herdwick Sheep')
	,(N'Hill Radnor Sheep')
	,(N'Hog Island Sheep')
	,(N'Hu Sheep')
	,(N'Icelandic Sheep')
	,(N'Ile-de-France Sheep')
	,(N'Istrian Pramenka Sheep')
	,(N'Jacob Sheep')
	,(N'Jezersko-Solcava Sheep')
	,(N'Kachhi Sheep')
	,(N'Kajli Sheep')
	,(N'Karakul Sheep')
	,(N'Katahdin Sheep')
	,(N'Kerry Hill Sheep')
	,(N'Kooka Sheep')
	,(N'Langhe Sheep')
	,(N'Lati Sheep')
	,(N'Leicester Longwool Sheep')
	,(N'Leineschaf Sheep')
	,(N'Lincoln Sheep')
	,(N'Llanwenog Sheep')
	,(N'Lleyn Sheep')
	,(N'Lohi Sheep')
	,(N'Lonk Sheep')
	,(N'Luzein Sheep')
	,(N'Manx Loaghtan Sheep')
	,(N'Masai Sheep')
	,(N'Massese Sheep')
	,(N'Medium-Wool Merino Sheep')
	,(N'Mehraban Sheep')
	,(N'Merinolandschaf Sheep')
	,(N'Moghani Sheep')
	,(N'Montadale Sheep')
	,(N'Morada Nova Sheep')
	,(N'Mouflon Sheep')
	,(N'Najdi Sheep')
	,(N'Navajo-Churro Sheep')
	,(N'Norfolk Horn Sheep')
	,(N'North Country Cheviot Sheep')
	,(N'Norwegian Fur Sheep')
	,(N'Old Norwegian Sheep')
	,(N'Orkney Sheep')
	,(N'Ossimi Sheep')
	,(N'Oxford Sheep')
	,(N'Pagliarola Sheep')
	,(N'Pelibüey Sheep')
	,(N'Perendale Sheep')
	,(N'Pinzirita Sheep')
	,(N'Pitt Island Sheep')
	,(N'Poll Merino Sheep')
	,(N'Polwarth Sheep')
	,(N'Polypay Sheep')
	,(N'Pomeranian Coarsewool Sheep')
	,(N'Portland Sheep')
	,(N'Priangan Sheep')
	,(N'Qashqai Sheep')
	,(N'Qinghai Black Tibetan Sheep')
	,(N'Qinghai Semifinewool Sheep')
	,(N'Quadrella Sheep')
	,(N'Quanglin Large-Tail Sheep')
	,(N'Rabo Largo Sheep')
	,(N'Racka Sheep')
	,(N'Rambouillet Sheep')
	,(N'Rasa Aragonesa Sheep')
	,(N'Red Engadine Sheep')
	,(N'Rhoenschaf Sheep')
	,(N'Rideau Arcott Sheep')
	,(N'Romanov Sheep')
	,(N'Romney Sheep')
	,(N'Rouge de I''Quest Sheep')
	,(N'Rough Fell Sheep')
	,(N'Royal White Sheep')
	,(N'Rya Sheep')
	,(N'Ryeland Sheep')
	,(N'Rygja Sheep')
	,(N'Sahel-type Sheep')
	,(N'Santa Cruz Sheep')
	,(N'Santa Inês Sheep')
	,(N'Sar Planina Sheep')
	,(N'Sardinian Sheep')
	,(N'Scottish Blackface Sheep')
	,(N'Shetland Sheep')
	,(N'Shropshire Sheep')
	,(N'Sicilian Barbary Sheep')
	,(N'Skudde Sheep')
	,(N'Soay Sheep')
	,(N'Somali Sheep')
	,(N'Sopravissana Sheep')
	,(N'South Afrian Mutton Merino Sheep')
	,(N'South African Merino Sheep')
	,(N'South Suffolk Sheep')
	,(N'South Wales Mountain Sheep')
	,(N'Southdown Sheep')
	,(N'Spaeslau Sheep')
	,(N'Spiegel Sheep')
	,(N'St. Croix (Virgin Island White) Sheep')
	,(N'Steigar Sheep')
	,(N'Steinschaf Sheep')
	,(N'Strong Wool Merino Sheep')
	,(N'Suffolk Sheep')
	,(N'Sumavska Sheep')
	,(N'Swaledale Sheep')
	,(N'Swedish Fur Sheep')
	,(N'Targhee Sheep')
	,(N'Teeswater Sheep')
	,(N'Texel Sheep')
	,(N'Thalli Sheep')
	,(N'Tong Sheep')
	,(N'Touabire Sheep')
	,(N'Tsurcana Sheep')
	,(N'Tunis Sheep')
	,(N'Tyrol Mountain Sheep')
	,(N'Uda Sheep')
	,(N'Ujumqin Sheep')
	,(N'Ushant Sheep')
	,(N'Valais Blacknose Sheep')
	,(N'Vendéen Sheep')
	,(N'Walachenschaf Sheep')
	,(N'Wallis Country Sheep')
	,(N'Waziri Sheep')
	,(N'Weisse Hornlose Heidschnucke Sheep')
	,(N'Welsh Hill Speckled Face Sheep')
	,(N'Welsh Mountain Badger Faced Sheep')
	,(N'Welsh Mountain Sheep')
	,(N'Wensleydale Sheep')
	,(N'West African Dwarf Sheep')
	,(N'White Suffolk Sheep')
	,(N'Whiteface Dartmoor Sheep')
	,(N'Whiteface Woodland Sheep')
	,(N'Wiltshire Horn Sheep')
	,(N'Xinjiang Finewool Sheep')
	,(N'Yankasa Sheep')
	,(N'Yemen White Sheep')
	,(N'Yemeni Sheep')
	,(N'Yiecheng Sheep')
	,(N'Yoroo Sheep')
	,(N'Yunnan Semifinewool Sheep')
	,(N'Zaghawa Sheep')
	,(N'Zagoria Sheep')
	,(N'Zaian Sheep')
	,(N'Zaire Long-Legged Sheep')
	,(N'Zakynthos Sheep')
	,(N'Zeeland Milk Sheep')
	,(N'Zel Sheep')
	,(N'Zelazna Sheep')
	,(N'Zemmour Sheep')
	,(N'Zeta Yellow Sheep')
	,(N'Zlatusha Sheep')
	,(N'Zoulay Sheep')
) v(breedname)
where not exists (
	select 1
	from breed
	where breed_species=@speciesid
	and breedname=v.breedname
)
go
