-- https://breeds.okstate.edu/horses
declare @speciesid int

select @speciesid=speciesid
from species
where speciesname='Equus caballus'

if @speciesid is null
	throw 50000,'Equus caballus was not found in species',1

insert into breed(breed_species,breedname)
select @speciesid,v.breedname
from (values
	 (N'Abyssinian Horses')
	,(N'Akhal-Teke Horses')
	,(N'Albanian Horses')
	,(N'Altai Horses')
	,(N'American Cream Draft Horses')
	,(N'American Creme and White Horses')
	,(N'American Walking Pony')
	,(N'Andalusian Horses')
	,(N'Andravida Horses')
	,(N'Anglo-Kabarda Horses')
	,(N'Appaloosa Horses')
	,(N'Araappaloosa Horses')
	,(N'Arabian Horses')
	,(N'Ardennes Horses')
	,(N'Argentine Criollo Horses')
	,(N'Asturian Horses')
	,(N'Australian Brumby Horses')
	,(N'Australian Stock Horses')
	,(N'Azteca Horses')
	,(N'Balearic Horse')
	,(N'Baluchi Horses')
	,(N'Ban-ei Horses')
	,(N'Banker Horses')
	,(N'Barb Horses')
	,(N'Bashkir Curly Horses')
	,(N'Bashkir Horses')
	,(N'Basotho Pony')
	,(N'Belgian Horses')
	,(N'Bhirum Pony')
	,(N'Bhotia Pony')
	,(N'Boer Horses')
	,(N'Bosnian Mountain Horses')
	,(N'Breton Horses')
	,(N'Buckskin Horses')
	,(N'Budyonny Horses')
	,(N'Byelorussian Harness Horses')
	,(N'Camargue Horses')
	,(N'Campolina Horses')
	,(N'Canadian Horses')
	,(N'Carthusian Horses')
	,(N'Caspian Horses')
	,(N'Cayuse Indian Pony')
	,(N'Cheju Horses')
	,(N'Chilean Corralero Horses')
	,(N'Chincoteague Pony')
	,(N'Cleveland Bay Horses')
	,(N'Clydesdale Horses')
	,(N'Colorado Ranger Horses')
	,(N'Connemara Pony')
	,(N'Criollo (Uruguay) Horses')
	,(N'Crioulo Horses')
	,(N'Dales Pony')
	,(N'Danube Horses')
	,(N'Dartmoor Pony')
	,(N'Deliboz Horses')
	,(N'Djerma Horses')
	,(N'Dole Horses')
	,(N'Dongola Horses')
	,(N'Dulmen Pony')
	,(N'Dutch Draft Horses')
	,(N'Dutch Warmblood Horses')
	,(N'East Bulgarian Horses')
	,(N'Egyptian Horses')
	,(N'Eriskay Pony')
	,(N'Estonian Native Horses')
	,(N'Exmoor Pony')
	,(N'Faeroes Pony Horses')
	,(N'Falabella Horses')
	,(N'Fell Pony')
	,(N'Finnhorses')
	,(N'Fleuve Horses')
	,(N'Florida Cracker Horses')
	,(N'Fouta Horses')
	,(N'Frederiksborg Horses')
	,(N'French Saddlebred Horses')
	,(N'French Trotter Horses')
	,(N'Friesian Horses')
	,(N'Galiceño Horses')
	,(N'Galician Pony')
	,(N'Gelderlander Horses')
	,(N'Gidran Horses')
	,(N'Golden America Saddlebred Horses')
	,(N'Gotland Horses')
	,(N'Groningen Horses')
	,(N'Guangxi Horses')
	,(N'Hackney Horses')
	,(N'Haflinger Horses')
	,(N'Hanoverian Horses')
	,(N'Hequ Horses')
	,(N'Highland Pony')
	,(N'Hokkaido Horses')
	,(N'Hucul Horses')
	,(N'Hungarian Warmblood Horses')
	,(N'Icelandic Horses')
	,(N'Iomud Horses')
	,(N'Irish Draught Horses')
	,(N'Jinzhou Horses')
	,(N'Jutland Horses')
	,(N'Kabarda Horses')
	,(N'Karabair Horses')
	,(N'Karabakh Horses')
	,(N'Kazakh Horses')
	,(N'Kerry Bog Pony')
	,(N'Kiger Mustang Horses')
	,(N'Kirdi Pony')
	,(N'Kisber Felver Horses')
	,(N'Kiso Horses')
	,(N'Kladruby Horses')
	,(N'Knabstrup Horses')
	,(N'Kushum Horses')
	,(N'Kustanai Horses')
	,(N'Latvian Horses')
	,(N'Lipizzan Horses')
	,(N'Lithuanian Heavy Draft Horses')
	,(N'Lokai Horses')
	,(N'Losino Horses')
	,(N'Lusitano Horses')
	,(N'M''Bayar Pony')
	,(N'Malopolski Horses')
	,(N'Mangalarga Horses')
	,(N'Marwari Horses')
	,(N'Mérens Pony')
	,(N'Messara Horses')
	,(N'Miniature Horses')
	,(N'Misaki Horses')
	,(N'Missouri Fox Trotting Horses')
	,(N'Miyako Horses')
	,(N'Mongolian Horses')
	,(N'Morab Horses')
	,(N'Morgan Horses')
	,(N'Moyle Horses')
	,(N'Murgese Horses')
	,(N'Mustang Horses')
	,(N'National Show Horses')
	,(N'New Forest Pony')
	,(N'New Kirgiz Horses')
	,(N'Newfoundland Pony')
	,(N'Nokota Horses')
	,(N'Noma Horses')
	,(N'Nooitgedacht Pony')
	,(N'Nordland Horses')
	,(N'Noric Horses')
	,(N'North Swedish Horses')
	,(N'Northeastern - Crioulo Horses')
	,(N'Norwegian Fjord Horses')
	,(N'Ob Pony')
	,(N'Oldenburg Horses')
	,(N'Orlov Trotter Horses')
	,(N'Paint Horses')
	,(N'Palomino Horses')
	,(N'Pantaneiro - Crioulo Horses')
	,(N'Paso Fino Horses')
	,(N'Percheron Horses')
	,(N'Peruvian Paso Horses')
	,(N'Pindos Pony')
	,(N'Pinia Horses')
	,(N'Pintabian Horses')
	,(N'Pinto Horses')
	,(N'Polish Konik Horses')
	,(N'Pony of the Americas')
	,(N'Pottok Horses')
	,(N'Przewalski Horses')
	,(N'Pyrenean Tarpan Horses')
	,(N'Qatgani Horses')
	,(N'Quarab Horses')
	,(N'Quarter Horses')
	,(N'Quarter Pony')
	,(N'Racking Horses')
	,(N'Rocky Mountain Horses')
	,(N'Russian Don Horses')
	,(N'Russian Heavy Draft Horses')
	,(N'Russian Trotter Horses')
	,(N'Saddlebred Horses')
	,(N'Sanhe Horses')
	,(N'Schleswiger Heavy Draft Horses')
	,(N'Schwarzwälder Fuchs Horses')
	,(N'Selle Francais Horses')
	,(N'Shagya Horses')
	,(N'Shetland Pony')
	,(N'Shire Horses')
	,(N'Single-Footing Horses')
	,(N'Skyros Pony')
	,(N'Somali Pony')
	,(N'Sorraia Horses')
	,(N'Soviet Heavy Draft Horses')
	,(N'Spanish Barb Horses')
	,(N'Spanish Mustang Horses')
	,(N'Spanish-Norman Horses')
	,(N'Standardbred Horses')
	,(N'Sudan Country-Bred Horses')
	,(N'Suffolk Horses')
	,(N'Swedish Warmblood Horses')
	,(N'Taishuh Horses')
	,(N'Tarpan Horses')
	,(N'Tawleed Horses')
	,(N'Tennessee Walking Horses')
	,(N'Tersk Horses')
	,(N'Thessalian Horses')
	,(N'Thoroughbred Horses')
	,(N'Tokara Horses')
	,(N'Tori Horses')
	,(N'Trakehner Horses')
	,(N'Ukrainian Saddle Horses')
	,(N'Vlaamperd Horses')
	,(N'Vladimir Heavy Draft Horses')
	,(N'Vyatka Horses')
	,(N'Welara Horses')
	,(N'Welsh Pony & Cob')
	,(N'West African Barb Horses')
	,(N'Western Sudan Pony')
	,(N'Wielkopolski Horses')
	,(N'Xilingol Horses')
	,(N'Yakut Horses')
	,(N'Yanqi Horses')
	,(N'Yili Horses')
	,(N'Yonaguni Horses')
	,(N'Zaniskari Pony')
	,(N'Zhemaichu Horses')
) v(breedname)
where not exists (
	select 1
	from breed
	where breed_species=@speciesid
	and breedname=v.breedname
)
go

select speciesid,speciesname
from species
where speciesname like 'Equus%'
order by speciesname
