insert into cat(catname) values('Microsoft Excel') -- 103
select * from cat
insert into act(act_cat,actname) values(103,'Review Session 1.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'How are chart sheets different from worksheets?')
insert into q(q_act,qname) values(@actid,'What is the cell reference for the cell located in the third column and fourth row of a worksheet?')
insert into q(q_act,qname) values(@actid,'What is the range reference for the block of cells D3 through E10?')
insert into q(q_act,qname) values(@actid,'What is the range reference for cells A1 through C5 and cells A8 through C12?')
insert into q(q_act,qname) values(@actid,'How is text aligned within a worksheet cell by default?')
insert into q(q_act,qname) values(@actid,'How would the number 00514 appear in a cell?')
insert into q(q_act,qname) values(@actid,'Cell B2 contains the entry May 3, 2025. Why doesn’t Excel consider this a text entry?')
insert into q(q_act,qname) values(@actid,'How do you autofit a column to match its longest cell entry?')
go

insert into act(act_cat,actname) values(103,'Review Session 1.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is the formula to add values in cells A1, B1, and C1? What function will achieve the same result?')
insert into q(q_act,qname) values(@actid,'What is the formula to count the number of numeric values in the range A1:A30?')
insert into q(q_act,qname) values(@actid,'If you insert cells into the range C1:D10, shifting the cells to the right, what is the new location of the data that was previously in cell F4?')
insert into q(q_act,qname) values(@actid,'Cell E11 contains the formula =SUM(E1:E10). How is the formula adjusted when a new row is inserted above row 5?')
insert into q(q_act,qname) values(@actid,'In the following function, which arguments are required and which arguments are optional:
<p><img src="Excel/1.2QuickCheck.png">')
insert into q(q_act,qname) values(@actid,'What is the formula to sum all the numeric values in column C.')
insert into q(q_act,qname) values(@actid,'Describe the four ways of viewing worksheet contents in Excel.')
insert into q(q_act,qname) values(@actid,'How are page breaks indicated in Page Break Preview?')
go
insert into act(act_cat,actname) values(103,'Review Session 2.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is the difference between a serif font and a sans serif font?')
insert into q(q_act,qname) values(@actid,'What is the difference between theme colors and standard colors?')
insert into q(q_act,qname) values(@actid,'A cell containing a number displays #######. Why does this occur, and what can you do to fix it?')
insert into q(q_act,qname) values(@actid,'How do you change the color of a worksheet tab?')
insert into q(q_act,qname) values(@actid,'What is the General format?')
insert into q(q_act,qname) values(@actid,'Describe the differences between the Accounting format and the Currency format.')
insert into q(q_act,qname) values(@actid,'The range B3:B13 is merged into a single cell. What is its cell reference?')
insert into q(q_act,qname) values(@actid,'How do you format text so that it is set vertically within the cell?')
go
insert into act(act_cat,actname) values(103,'Review Session 2.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'Describe two methods of applying the same format to different ranges.')
insert into q(q_act,qname) values(@actid,'Red is a standard color. What happens to red text when you change the workbook’s theme?')
insert into q(q_act,qname) values(@actid,'What is a conditional format?')
insert into q(q_act,qname) values(@actid,'How would you highlight the top 10% values in the range A1:C20?')
insert into q(q_act,qname) values(@actid,'How do you insert a manual page break in a worksheet?')
insert into q(q_act,qname) values(@actid,'What is a print area?')
insert into q(q_act,qname) values(@actid,'What are print titles?')
insert into q(q_act,qname) values(@actid,'Describe how to add the workbook file name to the center section of the footer on every page of the printout.')
go
insert into act(act_cat,actname) values(103,'Review Session 3.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'Write a formula to convert the number of days entered in cell B10 to seconds.')
insert into q(q_act,qname) values(@actid,'If 4/30/2025 and 5/31/2025 are the initial values in a range, list the next two values that AutoFill will insert.')
insert into q(q_act,qname) values(@actid,'Write a formula to round the value in cell A5 to the nearest multiple of 1000.')
insert into q(q_act,qname) values(@actid,'Write a formula to return the single value that is repeated the most times in the range Y1:Y100.')
insert into q(q_act,qname) values(@actid,'The range of values is defined as the maximum value minus the minimum value. Write a nested formula that calculates the range of values in the range Y1:Y100 and then rounds that value to the nearest integer.')
insert into q(q_act,qname) values(@actid,'Houses in a neighborhood usually sell for between $250,000 and $350,000 except for a large mansion that sold for $1,200,000. Which best expresses the typical home sales price: average or median? Why?')
insert into q(q_act,qname) values(@actid,'Stephen is entering hundreds of temperature values into a worksheet for a climate research project, and wants to speed up data entry by leaving freezing point values as blanks rather than typing zeroes. Explain why this will cause complications in the calculation of the average temperature.')
insert into q(q_act,qname) values(@actid,'Cell B2 contains the formula =SUME(A1:A100) with the name of the SUM function misspelled as SUME. What error value will appear in the cell?')
go
insert into act(act_cat,actname) values(103,'Review Session 3.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'Explain how to use the Quick Analysis tool to calculate a running total of the values in the range D1:D10.')
insert into q(q_act,qname) values(@actid,'You need to reference cell Q57 in a formula. What is its relative reference? What is its absolute reference? What are the two mixed references?')
insert into q(q_act,qname) values(@actid,'If cell R10 contains the formula =R1+R2 that is then copied to cell S20, what formula is entered in cell S20?')
insert into q(q_act,qname) values(@actid,'If cell R10 contains the formula =$R1+R$2 that is then copied to cell S20, what formula is entered in cell S20?')
insert into q(q_act,qname) values(@actid,'If cell Q3 is greater than cell Q4, you want to display the text “OK”; otherwise, display the text “RETRY”. Write the formula that accomplishes this.')
insert into q(q_act,qname) values(@actid,'Write the formula to perform an exact match lookup with the lookup value from cell G5 using a vertical lookup table located in the range A1:F50. Return the value from the third column of the table.')
insert into q(q_act,qname) values(@actid,'What is the difference between a what-if analysis by trial and error and by Goal Seek?')
go
insert into act(act_cat,actname) values(103,'Review Session 4.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'In a chart’s data source, where does Excel assume that category values are placed?')
insert into q(q_act,qname) values(@actid,'What three chart elements are included in a pie chart?')
insert into q(q_act,qname) values(@actid,'A data series contains values grouped into 12 categories. Would this data be better displayed as a pie chart or a column chart? Explain why.')
insert into q(q_act,qname) values(@actid,'A research firm wants to display the population of a state organized into five geographic locations. Which chart should it use? Explain why.')
insert into q(q_act,qname) values(@actid,'If the firm wants to display the total population growth of a state over a 10-year period organized by those five geographic locations, which chart type best displays this information? Explain why.')
insert into q(q_act,qname) values(@actid,'If the firm wants to display how the population of the geographic locations within the state changes over time as a percentage of the whole population, which chart type should it use? Explain why.')
insert into q(q_act,qname) values(@actid,'If the firm wants to display both the average annual income and the total population of the state over the 10-year period, what chart should it use and why?')
insert into q(q_act,qname) values(@actid,'What are major tick marks and minor tick marks?')
go
insert into act(act_cat,actname) values(103,'Review Session 4.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'A researcher wants to plot weight vs. blood pressure. Should the researcher use a line chart or a scatter chart? Explain why.')
insert into q(q_act,qname) values(@actid,'How would you select multiple graphic objects within a worksheet?')
insert into q(q_act,qname) values(@actid,'When would you use a Pareto chart?')
insert into q(q_act,qname) values(@actid,'When would you use a histogram?')
insert into q(q_act,qname) values(@actid,'Describe the three types of sparklines.')
insert into q(q_act,qname) values(@actid,'Under what circumstances would you use sparklines in a report?')
insert into q(q_act,qname) values(@actid,'Why would you not use a sparkline?')
insert into q(q_act,qname) values(@actid,'What are data bars? How do data bars differ from sparklines?')
go
insert into act(act_cat,actname) values(103,'Review Session 5.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'How do you create a worksheet group consisting of sheets that are not adjacent in a workbook?')
insert into q(q_act,qname) values(@actid,'Can a workbook have only one window?')
insert into q(q_act,qname) values(@actid,'How do you ungroup a worksheet group that consists of all the sheets in the workbook?')
insert into q(q_act,qname) values(@actid,'What is the 3-D cell reference to cell C20 in the Monday worksheet?')
insert into q(q_act,qname) values(@actid,'What is the absolute 3-D cell reference to cell C20 in the Monday worksheet?')
insert into q(q_act,qname) values(@actid,'What is the 3-D cell reference to cell C20 in the Monday through Friday worksheet group?')
insert into q(q_act,qname) values(@actid,'Write a formula that uses the MAX function to calculate the maximum value of cell C20 of the Monday through Friday worksheet group.')
go
insert into act(act_cat,actname) values(103,'Review Session 5.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is the external reference to cell C20 of the Final Report worksheet located in the Annual Statement.xlsx workbook?')
insert into q(q_act,qname) values(@actid,'What is the external reference to cell D10 of the Sunday worksheet located in the Weekly Report.xlsx workbook that is stored in the C:\Documents\Reports folder?')
insert into q(q_act,qname) values(@actid,'When would you paste a copied cell using the Paste Link option?')
insert into q(q_act,qname) values(@actid,'How do you check the status of a link within the current workbook to determine whether the link’s source file is accessible and up-to-date?')
insert into q(q_act,qname) values(@actid,'How does Excel indicate that a cell contains linked text?')
insert into q(q_act,qname) values(@actid,'What does Excel do when a hyperlink is clicked by the user?')
go
insert into act(act_cat,actname) values(103,'Review Session 5.3 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'Why is Report-Date not a valid named range?')
insert into q(q_act,qname) values(@actid,'What happens when you select a defined name in the Name box?')
insert into q(q_act,qname) values(@actid,'What is the difference between a defined name with global scope and one with local scope?')
insert into q(q_act,qname) values(@actid,'What is the expression to reference the local scope defined name TotalSales from the Final Report worksheet?')
insert into q(q_act,qname) values(@actid,'When would you create a template rather than just providing a coworker with the copy of your workbook?')
insert into q(q_act,qname) values(@actid,'What is displayed in the title bar for a workbook created from the EmployeeList.xltx template file?')
insert into q(q_act,qname) values(@actid,'By default, where does Excel store workbook templates?')
go
insert into act(act_cat,actname) values(103,'Review Session 6.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is a field? What is a record?')
insert into q(q_act,qname) values(@actid,'If you split the worksheet into panes at cell E3, how many panes are created?')
insert into q(q_act,qname) values(@actid,'What are the three freeze pane options?')
insert into q(q_act,qname) values(@actid,'When highlighting duplicate values with a conditional format, do the duplicate values have to be adjacent to each other?')
insert into q(q_act,qname) values(@actid,'Why is it not a good idea for a company to treat employee records with duplicate first and last names as duplicate records?')
insert into q(q_act,qname) values(@actid,'When an ascending sort order is used, how is a date-time field sorted?')
insert into q(q_act,qname) values(@actid,'If you want to sort employees by the value of the Hire Date field within each value of the Dept field, which field is the primary sort field? Which is the secondary sort field?')
insert into q(q_act,qname) values(@actid,'Before you can add subtotals to a data range, what must you first do with the data?')
go
insert into act(act_cat,actname) values(103,'Review Session 6.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What happens to worksheet rows that do not match the filter criteria? What happens to the data they contain?')
insert into q(q_act,qname) values(@actid,'When multiple filter buttons are used with a data range, how are criteria in different fields combined?')
insert into q(q_act,qname) values(@actid,'When would you use an advanced filter in place of the filter buttons?')
insert into q(q_act,qname) values(@actid,'What happens to banded rows in an Excel table when you insert or delete a row?')
insert into q(q_act,qname) values(@actid,'What is the reference to the Income field from the Employees table?')
insert into q(q_act,qname) values(@actid,'What is the formula to calculate the average of the Income field from the Employees table?')
insert into q(q_act,qname) values(@actid,'What is the structural reference to the table header row?')
go
insert into act(act_cat,actname) values(103,'Review Session 6.3 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What are two reasons for using slicers rather than filter buttons to filter data?')
insert into q(q_act,qname) values(@actid,'What are two reasons for using filter buttons rather than slicers to filter data?')
insert into q(q_act,qname) values(@actid,'Can slicers be used with both data ranges and Excel tables?')
insert into q(q_act,qname) values(@actid,'Can slicers be moved to any worksheet or external workbook?')
insert into q(q_act,qname) values(@actid,'Write a formula to calculate the sum of the filtered values from the Sales Price field in the Sales_Result table.')
insert into q(q_act,qname) values(@actid,'Write a formula to calculate the average of the filtered values from the Sales Price field in the Sales_Result table.')
insert into q(q_act,qname) values(@actid,'Write a formula to retrieve the value from the third field in the Sales_Result table that exactly matches the lookup value in cell B10.')
go
insert into act(act_cat,actname) values(103,'Review Session 7.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'A school gives out grades in the following ranges: F: 0 – < 60; D: 60 – < 70; C: 70 – < 80; B: 80 – < 90; A: 90 – 100. Create a vertical lookup table for this grade scale with the range values in the first column and the letter grades in the second.')
insert into q(q_act,qname) values(@actid,'What is the VLOOKUP function to perform an approximate match lookup for a test score of 83? Assume the lookup table is named GradeScale and the grades are in the second column.')
insert into q(q_act,qname) values(@actid,'What is the XLOOKUP function to perform an approximate match lookup for a test score of 83? Assume the column containing the lower end of the range of test scores is named TestScores and the range containing the grades is named Grades.')
insert into q(q_act,qname) values(@actid,'How does XLOOKUP differ from VLOOKUP in the placement of the column of lookup values?')
insert into q(q_act,qname) values(@actid,'How does XLOOKUP differ from VLOOKUP in how it handles failed matches?')
insert into q(q_act,qname) values(@actid,'What is the function to count the number of cells in the range B1:B50 that equal “B”?')
insert into q(q_act,qname) values(@actid,'What is the function to calculate the average of the cells in the range C1:C50 for which the adjacent cell in the range B1:B50 equals “B”?')
insert into q(q_act,qname) values(@actid,'What is the function to calculate the sum of the values in the range D1:D50 for which the adjacent value in the range A1:A50 equals “Senior” and the adjacent value in the range B1:B50 equals “B”?')
go
insert into act(act_cat,actname) values(103,'Review Session 7.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is a PivotTable?')
insert into q(q_act,qname) values(@actid,'What are the four primary areas of a PivotTable?')
insert into q(q_act,qname) values(@actid,'What default statistic is used for non-numeric data in the Values area of the PivotTable?')
insert into q(q_act,qname) values(@actid,'What default statistic is used for numeric data in the Values area of the PivotTable?')
insert into q(q_act,qname) values(@actid,'By default, how does a PivotTable arrange the categories in a row or column?')
insert into q(q_act,qname) values(@actid,'What happens when you place a date field in a row or column area?')
insert into q(q_act,qname) values(@actid,'What are two ways of filtering a PivotTable?')
go
insert into act(act_cat,actname) values(103,'Review Session 7.3 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What are the four areas of a PivotChart?')
insert into q(q_act,qname) values(@actid,'Can you create a PivotChart without a PivotTable?')
insert into q(q_act,qname) values(@actid,'Can any Excel chart type be turned into a PivotChart?')
insert into q(q_act,qname) values(@actid,'How do you apply the same slicer to multiple PivotTables?')
insert into q(q_act,qname) values(@actid,'Can a timeline slicer be used with Excel tables as well as PivotTables?')
insert into q(q_act,qname) values(@actid,'When you do you need to refresh a PivotTable?')
go
insert into act(act_cat,actname) values(103,'Review Session 8.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'Describe the difference between a variable expense and a fixed expense.')
insert into q(q_act,qname) values(@actid,'When does the break-even point occur?')
insert into q(q_act,qname) values(@actid,'What is a data table? What is an input cell? What is a result cell?')
insert into q(q_act,qname) values(@actid,'What is a one-variable data table? What is a two-variable data table?')
insert into q(q_act,qname) values(@actid,'How many result cells can you display with a one-variable data table? How many result cells can you display with a two-variable data table?')
insert into q(q_act,qname) values(@actid,'Cell E5 contains the formula =B10. You want to display the text “Profits” instead of the formula’s value. What custom format would you use?')
insert into q(q_act,qname) values(@actid,'What is an array formula?')
go
insert into act(act_cat,actname) values(103,'Review Session 8.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is one advantage of scenarios over data tables?')
insert into q(q_act,qname) values(@actid,'What should you do before creating a scenario report to make the entries on the report easier to interpret?')
insert into q(q_act,qname) values(@actid,'What are changing cells in a scenario?')
insert into q(q_act,qname) values(@actid,'Where are the result cells in a scenario?')
insert into q(q_act,qname) values(@actid,'What are the two types of scenario reports?')
insert into q(q_act,qname) values(@actid,'When would you use the filter button in a Scenario PivotTable report?')
go
insert into act(act_cat,actname) values(103,'Review Session 8.3 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is an add-in?')
insert into q(q_act,qname) values(@actid,'What are three options for the objective cell using Solver?')
insert into q(q_act,qname) values(@actid,'What is an objective cell? What is a variable cell?')
insert into q(q_act,qname) values(@actid,'What are the six types of constraints you can put on a cell in a Solver model?')
insert into q(q_act,qname) values(@actid,'What is an iterative process?')
insert into q(q_act,qname) values(@actid,'What is the difference between a binding constraint and a nonbinding constraint?')
insert into q(q_act,qname) values(@actid,'In the Solver report, what is meant by the term “slack”?')
go
insert into act(act_cat,actname) values(103,'Review Session 9.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'Explain the difference between positive and negative cash flow. If you borrow $20,000 from a bank, is that a positive or negative cash flow? Explain your answer.')
insert into q(q_act,qname) values(@actid,'What is the formula to calculate how much a savings account would be worth if the initial balance is $1,000 with monthly deposits of $75 for 10 years at 4.3% annual interest compounded monthly? What is the formula result?')
insert into q(q_act,qname) values(@actid,'You want a savings account to grow from $1,000 to $5,000 within two years. Assume the bank provides a 3.2% annual interest rate compounded monthly. What is the formula to calculate how much you must deposit each month to meet your savings goal? What is the formula result?')
insert into q(q_act,qname) values(@actid,'A business takes out a loan for $250,000 at 4.8% interest compounded monthly. If the business can afford to make monthly payments of only $1,500 on the loan, what is the formula to calculate the number of months required to repay the loan completely? What is the formula result?')
insert into q(q_act,qname) values(@actid,'Rerun your calculations from Question 4 assuming that the business can afford only a $1,000 monthly payment. What is the revised formula and resulting value? How do you explain the result?')
insert into q(q_act,qname) values(@actid,'A business takes out a 10-year loan for $250,000 at 5.3% interest compounded monthly. What is the formula to calculate the monthly payment and what is the resulting value?')
insert into q(q_act,qname) values(@actid,'For the loan conditions specified in Question 6, provide formulas to calculate the amount of the first payment used for interest and the amount of the first payment used to repay the principal. What are the resulting values?')
insert into q(q_act,qname) values(@actid,'For the loan conditions specified in Question 6, what are the formulas to calculate how much interest the business will pay in the first year and how much the business will repay toward the principal? What are the resulting values?')
insert into q(q_act,qname) values(@actid,'For the loan conditions in Question 6, calculate the total cost of the loan in terms of the total interest paid through the 10 years of the loan.')
go
insert into act(act_cat,actname) values(103,'Review Session 9.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'The first value in a linear trend is 50 and the fifth value is 475. What are the values of the second, third, and fourth items?')
insert into q(q_act,qname) values(@actid,'The first value in a growth trend is 50 and the fifth value is 475. What are the values of the second, third, and fourth items?')
insert into q(q_act,qname) values(@actid,'By what percentage do the values in Question 3 grow?')
insert into q(q_act,qname) values(@actid,'The first value in a series is 100. Extrapolate the next four values assuming a linear trend with a step size of 125.')
insert into q(q_act,qname) values(@actid,'The first value in a series is 100. Extrapolate the next four values if each value grows by 18% over the previous value.')
insert into q(q_act,qname) values(@actid,'A new business buys $20,000 worth of computer equipment. If the useful life of the equipment is 10 years with a salvage value of $3,000, provide the formula to determine the depreciation during the first year assuming straight-line depreciation. What is the formula result?')
insert into q(q_act,qname) values(@actid,'Provide the value of the asset in Year 1 through Year 5 using the depreciation schedule in Question 6.')
insert into q(q_act,qname) values(@actid,'Assume a declining balance depreciation for the computer equipment described in Question 6 and provide the formula and result to determine the depreciation in the first year.')
insert into q(q_act,qname) values(@actid,'Provide the value of the asset in Year 1 through Year 5 using the declining balance depreciation schedule in Question 8.')
go
insert into act(act_cat,actname) values(103,'Review Session 9.3 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'If you take out a loan for $200,000 that must be repaid in 10 years with quarterly payments of $7,200, what is the formula to calculate the annual interest rate of the loan? What is the result?')
insert into q(q_act,qname) values(@actid,'If the annual rate of return is 5%, is $95 today worth more than, less than, or the same as $100 a year from now? Show the formula and formula results you used to answer this question.')
insert into q(q_act,qname) values(@actid,'You receive $50 at the end of Year 1 from an investment, $75 at the end of Year 2, and $100 at the end of Year 3. If the rate of return is 6%, what is the present value of this investment? Show the formula and formula results you used to answer this question.')
insert into q(q_act,qname) values(@actid,'You spend $350 on an investment that pays $75 per year for the next six years. If you make the investment immediately, what is the net present value of the investment? Assume a 6% rate of return. Show the formula and formula results you used to answer this question.')
insert into q(q_act,qname) values(@actid,'Suppose that instead of spending $350 immediately on an investment, you spend $350 one year from now and then receive $75 per year for the next six years after that. What is the net present value assuming a 6% rate of return? Show the formula and formula results you used to answer this question.')
insert into q(q_act,qname) values(@actid,'Calculate the internal rate of return for the investment in Question 4. If another investment is available that pays a 7.3% rate of return, should you take it? Show the formula and formula results you used to answer this question.')
insert into q(q_act,qname) values(@actid,'When tracing an error with the auditing tools, what do red tracer arrows indicate?')
insert into q(q_act,qname) values(@actid,'What is the purpose of the Watch Window?')
go
insert into act(act_cat,actname) values(103,'Review Session 10.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is Business Intelligence?')
insert into q(q_act,qname) values(@actid,'What is a query?')
insert into q(q_act,qname) values(@actid,'What is a delimiter?')
insert into q(q_act,qname) values(@actid,'What is a CSV file?')
insert into q(q_act,qname) values(@actid,'How do you undo an action in the Power Query Editor?')
insert into q(q_act,qname) values(@actid,'What trendline should you add to a chart for data that increases or decreases quickly and then levels out?')
insert into q(q_act,qname) values(@actid,'What does a 95% confidence bound tell you about forecasted values?')
go
insert into act(act_cat,actname) values(103,'Review Session 10.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is a relational database?')
insert into q(q_act,qname) values(@actid,'What is a one-to-many relationship?')
insert into q(q_act,qname) values(@actid,'What is the advantage of placing large tables in the Data Model rather than in an Excel table that is visible in the workbook?')
insert into q(q_act,qname) values(@actid,'What is Power Pivot?')
insert into q(q_act,qname) values(@actid,'Describe how to create a table relationship in Power Pivot Diagram view.')
insert into q(q_act,qname) values(@actid,'In Diagram view, what does the arrow on the line connecting two tables indicate?')
insert into q(q_act,qname) values(@actid,'What is the advantage of using table relationships when creating a PivotTable report?')
go
insert into act(act_cat,actname) values(103,'Review Session 10.3 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is a hierarchy? How do you create a hierarchy?')
insert into q(q_act,qname) values(@actid,'What is the advantage of a hierarchy over an outline in a PivotTable design?')
insert into q(q_act,qname) values(@actid,'What are the two types of map charts?')
insert into q(q_act,qname) values(@actid,'Name three limitations of map charts.')
insert into q(q_act,qname) values(@actid,'What is a map tour?')
insert into q(q_act,qname) values(@actid,'Which 3D map type should you use to display locations with higher-sale totals in colors of greater intensity?')
insert into q(q_act,qname) values(@actid,'What is the Analyze Data tool?')
go
insert into act(act_cat,actname) values(103,'Review Session 11.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'How does the Compact layout differ from the Tabular layout?')
insert into q(q_act,qname) values(@actid,'What are two ways of manually sorting a PivotTable field?')
insert into q(q_act,qname) values(@actid,'When sorting a PivotTable by values in a field, how are the field values sorted by default?')
insert into q(q_act,qname) values(@actid,'When would you use a Label filter in a PivotTable?')
insert into q(q_act,qname) values(@actid,'When would you use a Value filter in a PivotTable?')
insert into q(q_act,qname) values(@actid,'How do you allow a PivotTable field to include both a Date filter and a Value filter?')
insert into q(q_act,qname) values(@actid,'When a PivotTable field is manually grouped, how does Excel treat the grouped items?')
insert into q(q_act,qname) values(@actid,'What does Excel do to date fields that are added to a PivotTable?')
go
insert into act(act_cat,actname) values(103,'Review Session 11.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'How do you display the rank (smallest to largest) of a PivotTable field?')
insert into q(q_act,qname) values(@actid,'Conditional formats can be applied to which parts of a PivotTable?')
insert into q(q_act,qname) values(@actid,'What is the PivotTable cache?')
insert into q(q_act,qname) values(@actid,'If motels are grouped by size in one PivotTable, how are they displayed in other PivotTables sharing the same cache?')
insert into q(q_act,qname) values(@actid,'How do you create a PivotTable with its own cache?')
insert into q(q_act,qname) values(@actid,'What is the difference between a calculated item and a calculated field?')
insert into q(q_act,qname) values(@actid,'How is the value of a calculated field summarized within a PivotTable?')
insert into q(q_act,qname) values(@actid,'What is a potential mistake you could make with calculated fields?')
go
insert into act(act_cat,actname) values(103,'Review Session 11.3 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is a standard PivotTable?')
insert into q(q_act,qname) values(@actid,'What function should you use to count the number of unique values within a field?')
insert into q(q_act,qname) values(@actid,'What is the difference between an implicit measure and an explicit measure?')
insert into q(q_act,qname) values(@actid,'Write a DAX formula to calculate the average of the Revenue field values in the Stays table.')
insert into q(q_act,qname) values(@actid,'What DAX function do you use to retrieve a value from a Data Model table based on the table relation?')
insert into q(q_act,qname) values(@actid,'What is the difference between the SUM and SUMX functions?')
insert into q(q_act,qname) values(@actid,'What function do you use to retrieve values from a PivotTable?')
insert into q(q_act,qname) values(@actid,'What function do you use to retrieve calculated values from the Data Model without the use of a PivotTable?')
insert into q(q_act,qname) values(@actid,'What are the three arguments of an Excel Database function?')
go
insert into act(act_cat,actname) values(103,'Review Session 12.1 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is WordArt?')
insert into q(q_act,qname) values(@actid,'What is a funnel chart?')
insert into q(q_act,qname) values(@actid,'Convert the formula =B1/B10 into a formula that calculates this value only if there is no error and otherwise displays the message “Error Found”.')
insert into q(q_act,qname) values(@actid,'Why would you use the IFERROR function?')
insert into q(q_act,qname) values(@actid,'What Excel function can be used to test whether a cell contains a numeric value?')
go
insert into act(act_cat,actname) values(103,'Review Session 12.2 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What are three responses to invalid data?')
insert into q(q_act,qname) values(@actid,'Why would you create an input message for a cell?')
insert into q(q_act,qname) values(@actid,'What are two ways of specifying a validation list?')
insert into q(q_act,qname) values(@actid,'Provide a custom validation expression that validates the data only if cell C10 is less than or equal cell D10.')
insert into q(q_act,qname) values(@actid,'When do you use the Circle Invalid Data command?')
insert into q(q_act,qname) values(@actid,'Can you rename a protected worksheet? Explain why or why not.')
insert into q(q_act,qname) values(@actid,'What is a locked cell? When does locking a cell take effect?')
go
insert into act(act_cat,actname) values(103,'Review Session 12.3 Quick Check')
declare @actid int=scope_identity()
insert into q(q_act,qname) values(@actid,'What is the Developer tab?')
insert into q(q_act,qname) values(@actid,'What is the Personal Macro workbook?')
insert into q(q_act,qname) values(@actid,'What is the one thing you should do before starting the macro recorder?')
insert into q(q_act,qname) values(@actid,'What is a macro-enabled workbook?')
insert into q(q_act,qname) values(@actid,'How do you assign a macro to a graphic shape or form button?')
insert into q(q_act,qname) values(@actid,'What is VBA?')
insert into q(q_act,qname) values(@actid,'What is a sub procedure?')
insert into q(q_act,qname) values(@actid,'What VBA command would you enter to clear the contents of the data in the range A1:A50?')
insert into q(q_act,qname) values(@actid,'What VBA command would you enter to display a message box with the message “End of Project”?')

go
update act set actlink='Review/Session/QuickCheck.cfm' where actlink is null

select * from act
select * from q where q_act=179



